// Generated by scripts/cacheTeamBadgeAssets.cjs; sources and hashes accompany the assets.
import badge0 from "../assets/team-badges/espn-101.png";
import badge1 from "../assets/team-badges/espn-102.png";
import badge2 from "../assets/team-badges/espn-103.png";
import badge3 from "../assets/team-badges/espn-10388.png";
import badge4 from "../assets/team-badges/espn-104.png";
import badge5 from "../assets/team-badges/espn-105.png";
import badge6 from "../assets/team-badges/espn-1068.png";
import badge7 from "../assets/team-badges/espn-107.png";
import badge8 from "../assets/team-badges/espn-109.png";
import badge9 from "../assets/team-badges/espn-110.png";
import badge10 from "../assets/team-badges/espn-111.png";
import badge11 from "../assets/team-badges/espn-112.png";
import badge12 from "../assets/team-badges/espn-113.png";
import badge13 from "../assets/team-badges/espn-114.png";
import badge14 from "../assets/team-badges/espn-11420.png";
import badge15 from "../assets/team-badges/espn-115.png";
import badge16 from "../assets/team-badges/espn-118.png";
import badge17 from "../assets/team-badges/espn-122.png";
import badge18 from "../assets/team-badges/espn-124.png";
import badge19 from "../assets/team-badges/espn-125.png";
import badge20 from "../assets/team-badges/espn-126.png";
import badge21 from "../assets/team-badges/espn-127.png";
import badge22 from "../assets/team-badges/espn-131.png";
import badge23 from "../assets/team-badges/espn-131701.png";
import badge24 from "../assets/team-badges/espn-133.png";
import badge25 from "../assets/team-badges/espn-134.png";
import badge26 from "../assets/team-badges/espn-137.png";
import badge27 from "../assets/team-badges/espn-138.png";
import badge28 from "../assets/team-badges/espn-145.png";
import badge29 from "../assets/team-badges/espn-148.png";
import badge30 from "../assets/team-badges/espn-152.png";
import badge31 from "../assets/team-badges/espn-1538.png";
import badge32 from "../assets/team-badges/espn-160.png";
import badge33 from "../assets/team-badges/espn-166.png";
import badge34 from "../assets/team-badges/espn-167.png";
import badge35 from "../assets/team-badges/espn-169.png";
import badge36 from "../assets/team-badges/espn-170.png";
import badge37 from "../assets/team-badges/espn-174.png";
import badge38 from "../assets/team-badges/espn-175.png";
import badge39 from "../assets/team-badges/espn-17530.png";
import badge40 from "../assets/team-badges/espn-176.png";
import badge41 from "../assets/team-badges/espn-17606.png";
import badge42 from "../assets/team-badges/espn-180.png";
import badge43 from "../assets/team-badges/espn-190.png";
import badge44 from "../assets/team-badges/espn-19001.png";
import badge45 from "../assets/team-badges/espn-1929.png";
import badge46 from "../assets/team-badges/espn-20301.png";
import badge47 from "../assets/team-badges/espn-22163.png";
import badge48 from "../assets/team-badges/espn-22165.png";
import badge49 from "../assets/team-badges/espn-22167.png";
import badge50 from "../assets/team-badges/espn-239.png";
import badge51 from "../assets/team-badges/espn-244.png";
import badge52 from "../assets/team-badges/espn-2502.png";
import badge53 from "../assets/team-badges/espn-2565.png";
import badge54 from "../assets/team-badges/espn-2572.png";
import badge55 from "../assets/team-badges/espn-2594.png";
import badge56 from "../assets/team-badges/espn-268.png";
import badge57 from "../assets/team-badges/espn-271.png";
import badge58 from "../assets/team-badges/espn-2720.png";
import badge59 from "../assets/team-badges/espn-274.png";
import badge60 from "../assets/team-badges/espn-2922.png";
import badge61 from "../assets/team-badges/espn-2925.png";
import badge62 from "../assets/team-badges/espn-2950.png";
import badge63 from "../assets/team-badges/espn-306.png";
import badge64 from "../assets/team-badges/espn-3243.png";
import badge65 from "../assets/team-badges/espn-3263.png";
import badge66 from "../assets/team-badges/espn-3307.png";
import badge67 from "../assets/team-badges/espn-333.png";
import badge68 from "../assets/team-badges/espn-336.png";
import badge69 from "../assets/team-badges/espn-337.png";
import badge70 from "../assets/team-badges/espn-340.png";
import badge71 from "../assets/team-badges/espn-3458.png";
import badge72 from "../assets/team-badges/espn-346.png";
import badge73 from "../assets/team-badges/espn-349.png";
import badge74 from "../assets/team-badges/espn-350.png";
import badge75 from "../assets/team-badges/espn-357.png";
import badge76 from "../assets/team-badges/espn-360.png";
import badge77 from "../assets/team-badges/espn-361.png";
import badge78 from "../assets/team-badges/espn-362.png";
import badge79 from "../assets/team-badges/espn-363.png";
import badge80 from "../assets/team-badges/espn-364.png";
import badge81 from "../assets/team-badges/espn-366.png";
import badge82 from "../assets/team-badges/espn-367.png";
import badge83 from "../assets/team-badges/espn-368.png";
import badge84 from "../assets/team-badges/espn-370.png";
import badge85 from "../assets/team-badges/espn-373.png";
import badge86 from "../assets/team-badges/espn-3751.png";
import badge87 from "../assets/team-badges/espn-3775.png";
import badge88 from "../assets/team-badges/espn-380.png";
import badge89 from "../assets/team-badges/espn-3812.png";
import badge90 from "../assets/team-badges/espn-382.png";
import badge91 from "../assets/team-badges/espn-383.png";
import badge92 from "../assets/team-badges/espn-384.png";
import badge93 from "../assets/team-badges/espn-3841.png";
import badge94 from "../assets/team-badges/espn-386.png";
import badge95 from "../assets/team-badges/espn-388.png";
import badge96 from "../assets/team-badges/espn-390.png";
import badge97 from "../assets/team-badges/espn-393.png";
import badge98 from "../assets/team-badges/espn-395.png";
import badge99 from "../assets/team-badges/espn-398.png";
import badge100 from "../assets/team-badges/espn-3997.png";
import badge101 from "../assets/team-badges/espn-4007.png";
import badge102 from "../assets/team-badges/espn-4057.png";
import badge103 from "../assets/team-badges/espn-437.png";
import badge104 from "../assets/team-badges/espn-438.png";
import badge105 from "../assets/team-badges/espn-4771.png";
import badge106 from "../assets/team-badges/espn-5002.png";
import badge107 from "../assets/team-badges/espn-502.png";
import badge108 from "../assets/team-badges/espn-510.png";
import badge109 from "../assets/team-badges/espn-6086.png";
import badge110 from "../assets/team-badges/espn-6672.png";
import badge111 from "../assets/team-badges/espn-6851.png";
import badge112 from "../assets/team-badges/espn-7102.png";
import badge113 from "../assets/team-badges/espn-7109.png";
import badge114 from "../assets/team-badges/espn-7116.png";
import badge115 from "../assets/team-badges/espn-7120.png";
import badge116 from "../assets/team-badges/espn-7476.png";
import badge117 from "../assets/team-badges/espn-7477.png";
import badge118 from "../assets/team-badges/espn-7868.png";
import badge119 from "../assets/team-badges/espn-7911.png";
import badge120 from "../assets/team-badges/espn-8222.png";
import badge121 from "../assets/team-badges/espn-85.png";
import badge122 from "../assets/team-badges/espn-86.png";
import badge123 from "../assets/team-badges/espn-87.png";
import badge124 from "../assets/team-badges/espn-88.png";
import badge125 from "../assets/team-badges/espn-89.png";
import badge126 from "../assets/team-badges/espn-90.png";
import badge127 from "../assets/team-badges/espn-9169.png";
import badge128 from "../assets/team-badges/espn-93.png";
import badge129 from "../assets/team-badges/espn-94.png";
import badge130 from "../assets/team-badges/espn-96.png";
import badge131 from "../assets/team-badges/espn-97.png";
import badge132 from "../assets/team-badges/espn-9726.png";
import badge133 from "../assets/team-badges/espn-987.png";
import badge134 from "../assets/team-badges/espn-99.png";
import badge135 from "../assets/team-badges/espn-9967.png";
import badge136 from "../assets/team-badges/flag-ae.png";
import badge137 from "../assets/team-badges/flag-ar.png";
import badge138 from "../assets/team-badges/flag-at.png";
import badge139 from "../assets/team-badges/flag-au.png";
import badge140 from "../assets/team-badges/flag-ba.png";
import badge141 from "../assets/team-badges/flag-be.png";
import badge142 from "../assets/team-badges/flag-bg.png";
import badge143 from "../assets/team-badges/flag-bo.png";
import badge144 from "../assets/team-badges/flag-br.png";
import badge145 from "../assets/team-badges/flag-ca.png";
import badge146 from "../assets/team-badges/flag-cd.png";
import badge147 from "../assets/team-badges/flag-ch.png";
import badge148 from "../assets/team-badges/flag-ci.png";
import badge149 from "../assets/team-badges/flag-cl.png";
import badge150 from "../assets/team-badges/flag-cn.png";
import badge151 from "../assets/team-badges/flag-co.png";
import badge152 from "../assets/team-badges/flag-cr.png";
import badge153 from "../assets/team-badges/flag-cv.png";
import badge154 from "../assets/team-badges/flag-cw.png";
import badge155 from "../assets/team-badges/flag-cy.png";
import badge156 from "../assets/team-badges/flag-cz.png";
import badge157 from "../assets/team-badges/flag-de.png";
import badge158 from "../assets/team-badges/flag-dk.png";
import badge159 from "../assets/team-badges/flag-dz.png";
import badge160 from "../assets/team-badges/flag-ec.png";
import badge161 from "../assets/team-badges/flag-eg.png";
import badge162 from "../assets/team-badges/flag-es.png";
import badge163 from "../assets/team-badges/flag-fi.png";
import badge164 from "../assets/team-badges/flag-fr.png";
import badge165 from "../assets/team-badges/flag-gb-eng.png";
import badge166 from "../assets/team-badges/flag-gb-nir.png";
import badge167 from "../assets/team-badges/flag-gb-sct.png";
import badge168 from "../assets/team-badges/flag-gb-wls.png";
import badge169 from "../assets/team-badges/flag-ge.png";
import badge170 from "../assets/team-badges/flag-gh.png";
import badge171 from "../assets/team-badges/flag-gr.png";
import badge172 from "../assets/team-badges/flag-hk.png";
import badge173 from "../assets/team-badges/flag-hr.png";
import badge174 from "../assets/team-badges/flag-ht.png";
import badge175 from "../assets/team-badges/flag-hu.png";
import badge176 from "../assets/team-badges/flag-id.png";
import badge177 from "../assets/team-badges/flag-ie.png";
import badge178 from "../assets/team-badges/flag-iq.png";
import badge179 from "../assets/team-badges/flag-ir.png";
import badge180 from "../assets/team-badges/flag-is.png";
import badge181 from "../assets/team-badges/flag-it.png";
import badge182 from "../assets/team-badges/flag-jo.png";
import badge183 from "../assets/team-badges/flag-jp.png";
import badge184 from "../assets/team-badges/flag-kp.png";
import badge185 from "../assets/team-badges/flag-kr.png";
import badge186 from "../assets/team-badges/flag-kz.png";
import badge187 from "../assets/team-badges/flag-ma.png";
import badge188 from "../assets/team-badges/flag-me.png";
import badge189 from "../assets/team-badges/flag-mk.png";
import badge190 from "../assets/team-badges/flag-mo.png";
import badge191 from "../assets/team-badges/flag-mv.png";
import badge192 from "../assets/team-badges/flag-mx.png";
import badge193 from "../assets/team-badges/flag-my.png";
import badge194 from "../assets/team-badges/flag-ng.png";
import badge195 from "../assets/team-badges/flag-nl.png";
import badge196 from "../assets/team-badges/flag-no.png";
import badge197 from "../assets/team-badges/flag-nz.png";
import badge198 from "../assets/team-badges/flag-pa.png";
import badge199 from "../assets/team-badges/flag-pe.png";
import badge200 from "../assets/team-badges/flag-ph.png";
import badge201 from "../assets/team-badges/flag-pl.png";
import badge202 from "../assets/team-badges/flag-pt.png";
import badge203 from "../assets/team-badges/flag-py.png";
import badge204 from "../assets/team-badges/flag-qa.png";
import badge205 from "../assets/team-badges/flag-ro.png";
import badge206 from "../assets/team-badges/flag-rs.png";
import badge207 from "../assets/team-badges/flag-sa.png";
import badge208 from "../assets/team-badges/flag-se.png";
import badge209 from "../assets/team-badges/flag-sg.png";
import badge210 from "../assets/team-badges/flag-si.png";
import badge211 from "../assets/team-badges/flag-sk.png";
import badge212 from "../assets/team-badges/flag-sn.png";
import badge213 from "../assets/team-badges/flag-th.png";
import badge214 from "../assets/team-badges/flag-tn.png";
import badge215 from "../assets/team-badges/flag-tr.png";
import badge216 from "../assets/team-badges/flag-us.png";
import badge217 from "../assets/team-badges/flag-uy.png";
import badge218 from "../assets/team-badges/flag-uz.png";
import badge219 from "../assets/team-badges/flag-ve.png";
import badge220 from "../assets/team-badges/flag-vn.png";
import badge221 from "../assets/team-badges/flag-xk.png";
import badge222 from "../assets/team-badges/flag-za.png";
import badge223 from "../assets/team-badges/fujieda-myfc.png";
import badge224 from "../assets/team-badges/kleague-k10.png";
import badge225 from "../assets/team-badges/kleague-k18.png";
import badge226 from "../assets/team-badges/kleague-k27.png";
export const teamBadgeAssets: Record<string, string> = {
  "espn-101": badge0,
  "espn-102": badge1,
  "espn-103": badge2,
  "espn-10388": badge3,
  "espn-104": badge4,
  "espn-105": badge5,
  "espn-1068": badge6,
  "espn-107": badge7,
  "espn-109": badge8,
  "espn-110": badge9,
  "espn-111": badge10,
  "espn-112": badge11,
  "espn-113": badge12,
  "espn-114": badge13,
  "espn-11420": badge14,
  "espn-115": badge15,
  "espn-118": badge16,
  "espn-122": badge17,
  "espn-124": badge18,
  "espn-125": badge19,
  "espn-126": badge20,
  "espn-127": badge21,
  "espn-131": badge22,
  "espn-131701": badge23,
  "espn-133": badge24,
  "espn-134": badge25,
  "espn-137": badge26,
  "espn-138": badge27,
  "espn-145": badge28,
  "espn-148": badge29,
  "espn-152": badge30,
  "espn-1538": badge31,
  "espn-160": badge32,
  "espn-166": badge33,
  "espn-167": badge34,
  "espn-169": badge35,
  "espn-170": badge36,
  "espn-174": badge37,
  "espn-175": badge38,
  "espn-17530": badge39,
  "espn-176": badge40,
  "espn-17606": badge41,
  "espn-180": badge42,
  "espn-190": badge43,
  "espn-19001": badge44,
  "espn-1929": badge45,
  "espn-20301": badge46,
  "espn-22163": badge47,
  "espn-22165": badge48,
  "espn-22167": badge49,
  "espn-239": badge50,
  "espn-244": badge51,
  "espn-2502": badge52,
  "espn-2565": badge53,
  "espn-2572": badge54,
  "espn-2594": badge55,
  "espn-268": badge56,
  "espn-271": badge57,
  "espn-2720": badge58,
  "espn-274": badge59,
  "espn-2922": badge60,
  "espn-2925": badge61,
  "espn-2950": badge62,
  "espn-306": badge63,
  "espn-3243": badge64,
  "espn-3263": badge65,
  "espn-3307": badge66,
  "espn-333": badge67,
  "espn-336": badge68,
  "espn-337": badge69,
  "espn-340": badge70,
  "espn-3458": badge71,
  "espn-346": badge72,
  "espn-349": badge73,
  "espn-350": badge74,
  "espn-357": badge75,
  "espn-360": badge76,
  "espn-361": badge77,
  "espn-362": badge78,
  "espn-363": badge79,
  "espn-364": badge80,
  "espn-366": badge81,
  "espn-367": badge82,
  "espn-368": badge83,
  "espn-370": badge84,
  "espn-373": badge85,
  "espn-3751": badge86,
  "espn-3775": badge87,
  "espn-380": badge88,
  "espn-3812": badge89,
  "espn-382": badge90,
  "espn-383": badge91,
  "espn-384": badge92,
  "espn-3841": badge93,
  "espn-386": badge94,
  "espn-388": badge95,
  "espn-390": badge96,
  "espn-393": badge97,
  "espn-395": badge98,
  "espn-398": badge99,
  "espn-3997": badge100,
  "espn-4007": badge101,
  "espn-4057": badge102,
  "espn-437": badge103,
  "espn-438": badge104,
  "espn-4771": badge105,
  "espn-5002": badge106,
  "espn-502": badge107,
  "espn-510": badge108,
  "espn-6086": badge109,
  "espn-6672": badge110,
  "espn-6851": badge111,
  "espn-7102": badge112,
  "espn-7109": badge113,
  "espn-7116": badge114,
  "espn-7120": badge115,
  "espn-7476": badge116,
  "espn-7477": badge117,
  "espn-7868": badge118,
  "espn-7911": badge119,
  "espn-8222": badge120,
  "espn-85": badge121,
  "espn-86": badge122,
  "espn-87": badge123,
  "espn-88": badge124,
  "espn-89": badge125,
  "espn-90": badge126,
  "espn-9169": badge127,
  "espn-93": badge128,
  "espn-94": badge129,
  "espn-96": badge130,
  "espn-97": badge131,
  "espn-9726": badge132,
  "espn-987": badge133,
  "espn-99": badge134,
  "espn-9967": badge135,
  "flag-ae": badge136,
  "flag-ar": badge137,
  "flag-at": badge138,
  "flag-au": badge139,
  "flag-ba": badge140,
  "flag-be": badge141,
  "flag-bg": badge142,
  "flag-bo": badge143,
  "flag-br": badge144,
  "flag-ca": badge145,
  "flag-cd": badge146,
  "flag-ch": badge147,
  "flag-ci": badge148,
  "flag-cl": badge149,
  "flag-cn": badge150,
  "flag-co": badge151,
  "flag-cr": badge152,
  "flag-cv": badge153,
  "flag-cw": badge154,
  "flag-cy": badge155,
  "flag-cz": badge156,
  "flag-de": badge157,
  "flag-dk": badge158,
  "flag-dz": badge159,
  "flag-ec": badge160,
  "flag-eg": badge161,
  "flag-es": badge162,
  "flag-fi": badge163,
  "flag-fr": badge164,
  "flag-gb-eng": badge165,
  "flag-gb-nir": badge166,
  "flag-gb-sct": badge167,
  "flag-gb-wls": badge168,
  "flag-ge": badge169,
  "flag-gh": badge170,
  "flag-gr": badge171,
  "flag-hk": badge172,
  "flag-hr": badge173,
  "flag-ht": badge174,
  "flag-hu": badge175,
  "flag-id": badge176,
  "flag-ie": badge177,
  "flag-iq": badge178,
  "flag-ir": badge179,
  "flag-is": badge180,
  "flag-it": badge181,
  "flag-jo": badge182,
  "flag-jp": badge183,
  "flag-kp": badge184,
  "flag-kr": badge185,
  "flag-kz": badge186,
  "flag-ma": badge187,
  "flag-me": badge188,
  "flag-mk": badge189,
  "flag-mo": badge190,
  "flag-mv": badge191,
  "flag-mx": badge192,
  "flag-my": badge193,
  "flag-ng": badge194,
  "flag-nl": badge195,
  "flag-no": badge196,
  "flag-nz": badge197,
  "flag-pa": badge198,
  "flag-pe": badge199,
  "flag-ph": badge200,
  "flag-pl": badge201,
  "flag-pt": badge202,
  "flag-py": badge203,
  "flag-qa": badge204,
  "flag-ro": badge205,
  "flag-rs": badge206,
  "flag-sa": badge207,
  "flag-se": badge208,
  "flag-sg": badge209,
  "flag-si": badge210,
  "flag-sk": badge211,
  "flag-sn": badge212,
  "flag-th": badge213,
  "flag-tn": badge214,
  "flag-tr": badge215,
  "flag-us": badge216,
  "flag-uy": badge217,
  "flag-uz": badge218,
  "flag-ve": badge219,
  "flag-vn": badge220,
  "flag-xk": badge221,
  "flag-za": badge222,
  "fujieda-myfc": badge223,
  "kleague-k10": badge224,
  "kleague-k18": badge225,
  "kleague-k27": badge226,
};
