'use strict';
const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const compile=(file,req,globals={})=>{const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(require.resolve(file),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{module,exports:module.exports,require:req,URL,URLSearchParams,Date,Intl,AbortController,setTimeout,clearTimeout,...globals});return module.exports;};
const words=n=>n==null||typeof n==='boolean'?'':Array.isArray(n)?n.map(words).join(''):typeof n==='object'?words(n.props?.children):String(n);
const nodes=(n,p)=>n&&typeof n==='object'?(Array.isArray(n)?n.flatMap(v=>nodes(v,p)):[...(p(n)?[n]:[]),...nodes(n.props?.children,p)]):[];
const fixtures=[{id:'sporttery_a',sourceMatchId:'a',matchNo:'周二001',businessDate:'2026-09-22',homeTeamName:'阿森纳',homeTeamNameEn:'Arsenal',awayTeamName:'切尔西',leagueName:'英超',status:'SCHEDULED',kickoffTime:'2026-09-22T12:00:00Z',odds:{home:1.8,draw:3.2,away:null},oddsSource:'500-sp',sourceUpdatedAt:'2026-09-22T05:55:00Z'},{id:'sporttery_b',sourceMatchId:'b',matchNo:'周三002',businessDate:'2026-09-23',homeTeamName:'乌迪内斯',awayTeamName:'博洛尼亚',leagueName:'意甲',status:'SCHEDULED',kickoffTime:'2026-09-23T12:00:00Z',odds:{home:2.1,draw:null,away:3.3}}];
const overview=()=>({businessDate:'2026-09-22',sourceUpdatedAt:'2026-09-22T05:59:00Z',stale:false,matches:structuredClone(fixtures),review:{updatedAt:'2026-09-22T05:00:00Z',summary:{settled:20,won:8,pending:4,hitRate:.4},example:{decisionId:'decision_saved',matchId:'sporttery_review',homeTeamName:'历史主队',awayTeamName:'历史客队',publishedAt:'2026-09-21T00:00:00Z',cutoffTime:'2026-09-21T01:00:00Z',tipCode:'2',odds:2.35,state:'LOST',score:'2-0',quoteSource:'official-archived-sp',quoteObservedAt:'2026-09-20T23:50:00Z'}}});
async function harness({data=overview(),failure=false,matchId,route={pathname:'/fixtures',search:'',hash:'',state:null},user=null}={}){
 let cursor=0,search=route.search,effectStarted=false;const cells=[],effects=[],fetches=[];
 const accountApi=compile('../src/services/accountApi.ts',id=>id==='./runtimeUrls'?{buildApiUrl:p=>p}:require(id));
 const mod=compile('../src/pages/PublicBrowse.tsx',id=>{
 if(id==='react')return{useState:initial=>{const n=cursor++;if(!(n in cells))cells[n]=typeof initial==='function'?initial():initial;return[cells[n],v=>{cells[n]=typeof v==='function'?v(cells[n]):v;}];},useEffect:fn=>{if(!effectStarted){effects.push(fn);effectStarted=true;}}};
 if(id==='react/jsx-runtime')return{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props}),Fragment:'fragment'};
 if(id==='react-router-dom')return{Link:'a',useLocation:()=>({...route,search}),useParams:()=>({matchId}),useSearchParams:()=>[new URLSearchParams(search),(next)=>{search='?'+next.toString();}]};
 if(id==='lucide-react')return new Proxy({},{get:()=>()=>null});if(id.endsWith('/AccountContext'))return{useAccount:()=>({user})};if(id.endsWith('/AppContextCore'))return{useApp:()=>({language:'zh'})};if(id.endsWith('/FollowButton'))return{FollowButton:'follow'};if(id.endsWith('/TeamBadge'))return{TeamBadge:'badge'};if(id.endsWith('/runtimeUrls'))return{buildApiUrl:p=>p};if(id.endsWith('/accountApi'))return accountApi;if(id.endsWith('.css'))return{};throw Error(id);
 },{fetch:async(url)=>{fetches.push(url);if(failure)return{ok:false,status:503};return{ok:true,json:async()=>url.includes('/matches/')?{match:data.matches[0]}:data};}});
 const render=()=>{cursor=0;return mod.PublicBrowse();};let tree=render();assert.match(words(tree),/正在读取/);effects.forEach(fn=>fn());await new Promise(r=>setTimeout(r,0));await new Promise(r=>setTimeout(r,0));return{render,fetches,get search(){return search;}};
}
const cards=t=>nodes(t,n=>n.type==='article'&&n.props.className==='public-fixture');
test('public fixtures select current business date and keep search/date in URL',async()=>{const u=await harness();let t=u.render();assert.equal(cards(t).length,1);assert.match(words(cards(t)[0]),/阿森纳/);nodes(t,n=>n.type==='select')[0].props.onChange({target:{value:'2026-09-23'}});t=u.render();assert.equal(cards(t).length,1);assert.match(words(cards(t)[0]),/乌迪内斯/);assert.match(u.search,/date=2026-09-23/);nodes(t,n=>n.type==='input')[0].props.onChange({target:{value:'  博洛尼亚  '}});assert.equal(cards(u.render()).length,1);assert.match(u.search,/q=/);});
test('case-insensitive English search and clear-filter empty action are usable',async()=>{const u=await harness();let t=u.render();nodes(t,n=>n.type==='input')[0].props.onChange({target:{value:' ARSENAL '}});assert.equal(cards(u.render()).length,1);nodes(u.render(),n=>n.type==='input')[0].props.onChange({target:{value:'不存在'}});t=u.render();assert.equal(cards(t).length,0);assert.match(words(t),/没有匹配的比赛/);nodes(t,n=>n.type==='button'&&words(n)==='清除搜索')[0].props.onClick();assert.equal(cards(u.render()).length,1);});
test('public quotes label exact source and retain missing odds instead of invented numbers',async()=>{const u=await harness(),t=u.render(),c=cards(t)[0];assert.match(words(c),/报价来源：500-sp/);assert.match(words(c),/记录时间：09\/22 13:55/);assert.match(words(c),/1\.80/);assert.match(words(c),/客胜—/);assert.doesNotMatch(words(c),/官方赔率/);nodes(t,n=>n.type==='select')[0].props.onChange({target:{value:'2026-09-23'}});assert.match(words(cards(u.render())[0]),/来源未标注/);});
test('network failure has retry and does not announce zero fixtures as a successful empty day',async()=>{const u=await harness({failure:true}),text=words(u.render());assert.match(text,/内容暂时读取失败，请重试/);assert.doesNotMatch(text,/这个竞彩日暂无比赛/);assert.equal(nodes(u.render(),n=>n.type==='button'&&words(n)==='重试').length,1);});
test('public historical sample reports actual loss and auditable quote fields; missing totals stay unknown',async()=>{const data=overview();data.review.summary=null;const u=await harness({data,route:{pathname:'/review',search:'',hash:'',state:null}}),t=u.render(),text=words(t);assert.equal(cards(t).length,0);assert.match(text,/未命中/);assert.match(text,/official-archived-sp/);assert.match(text,/decision_saved/);assert.match(text,/历史命中率—/);assert.doesNotMatch(text,/历史命中率0\.0%/);});
test('unknown requested date stays visible in picker and yields genuine no-fixture state',async()=>{const u=await harness({route:{pathname:'/fixtures',search:'?date=2026-10-01',hash:'',state:null}}),t=u.render();assert.equal(cards(t).length,0);assert.match(words(t),/2026-10-01 · 暂无赛程/);assert.match(words(t),/这个竞彩日暂无比赛/);});
test('public detail drops unsafe back path and preserves its route as the sign-in return',async()=>{const u=await harness({matchId:'sporttery_a',route:{pathname:'/match/sporttery_a',search:'?tab=history',hash:'#evidence',state:{fromPath:'/\\evil.example'}}}),t=u.render();assert.equal(nodes(t,n=>n.type==='a'&&n.props.className==='public-back')[0].props.to,'/fixtures');assert.equal(nodes(t,n=>n.type==='a'&&n.props.className==='public-cta')[0].props.to,'/auth?returnTo=%2Fmatch%2Fsporttery_a%3Ftab%3Dhistory%23evidence');assert.equal(u.fetches.length,2);});

test('public sample includes only actual published probability values and preserves missing outcomes',async()=>{const data=overview();data.review.example.probabilities={'1':.4,X:null,'2':.35};const u=await harness({data,route:{pathname:'/review',search:'',hash:'',state:null}}),t=u.render(),sample=nodes(t,n=>n.props?.className==='public-example')[0];assert.match(words(sample),/发布时胜平负模型概率（参考）/);assert.match(words(sample),/主胜40\.0%/);assert.match(words(sample),/平局—/);assert.match(words(sample),/客胜35\.0%/);});
