'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { analyzeHandicap, settledHandicap, integerLine, poissonShape } = require('../src/services/handicapMargin.cjs');
const { makeDecision, validDecision, chooseCombo } = require('../scripts/recommendationPlatform/decision.cjs');
const { settleDecision, collectResults, key } = require('../scripts/recommendationPlatform/results.cjs');
const { attachProspectiveForecastInputs } = require('../src/services/prospectiveForecastInput.cjs');
const { createRuntime } = require('../scripts/recommendationPlatform/runtime.cjs');
const { NOW, match, publication, validators, memoryPorts } = require('./recommendationFixture.cjs');
const ctx = { now: NOW, publication: publication(NOW) };
const smallWin = [ { home:1, away:0, probability:.46 }, { home:2, away:0, probability:.18 }, { home:0, away:0, probability:.20 }, { home:0, away:1, probability:.16 } ];
const largeWin = [ { home:1, away:0, probability:.16 }, { home:3, away:0, probability:.55 }, { home:0, away:0, probability:.19 }, { home:0, away:1, probability:.10 } ];
const analyze = (scoreRows, hadProbabilities, line=-1) => analyzeHandicap({scoreRows,hadProbabilities,line});
function fixture(id=1, at=NOW) {
  const m = match(id, at); m.handicapLine = '-1'; m.handicapOddsSource = 'sporttery:HHAD';
  m.handicapOddsUpdatedAt = new Date(at).toISOString();
  m.probabilityModel.calculationTrace = {poisson:{lambdas:{home:1.8,away:.7}}};
  m.probabilityModel.handicap = {line:'-1'};
  return m;
}
const decision=m=>makeDecision(m,ctx).decision;
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} differs from ${b}`);
test('home -1, exact one-goal win becomes handicap draw',()=>assert.equal(settledHandicap(2,1,-1),'X'));
test('home -1, two-goal win becomes handicap home',()=>assert.equal(settledHandicap(3,1,-1),'1'));
test('home -1, draw or defeat becomes handicap away',()=>{assert.equal(settledHandicap(1,1,-1),'2');assert.equal(settledHandicap(0,1,-1),'2');});
test('home -2: one-goal win loses, two-goal win draws, three-goal win covers',()=>{assert.equal(settledHandicap(1,0,-2),'2');assert.equal(settledHandicap(2,0,-2),'X');assert.equal(settledHandicap(3,0,-2),'1');});
test('home +1 and +2 mirror losing margins correctly',()=>{assert.equal(settledHandicap(0,1,1),'X');assert.equal(settledHandicap(0,2,1),'2');assert.equal(settledHandicap(0,1,2),'1');assert.equal(settledHandicap(0,2,2),'X');assert.equal(settledHandicap(0,3,2),'2');});
test('zero handicap equals ordinary HAD',()=>{assert.equal(settledHandicap(1,0,0),'1');assert.equal(settledHandicap(0,0,0),'X');assert.equal(settledHandicap(0,1,0),'2');});
test('Asian fractions, unknown line and malformed score are not accepted as HHAD',()=>{for(const v of [null,'',true,'1/1.5',.5,-.25])assert.equal(integerLine(v),null);assert.equal(settledHandicap(-1,0,-1),null);});
test('explicit Unicode plus/minus signs stay signed',()=>{assert.equal(integerLine('＋2'),2);assert.equal(integerLine('−2'),-2);});
test('home win with strong exact-one-goal mass recommends handicap draw',()=>{const a=analyze(smallWin,{'1':.64,X:.2,'2':.16});assert.equal(a.tipCode,'X');near(a.probabilities.X,.46);near(a.probabilities['1'],.18);near(a.probabilities['2'],.36);});
test('cover-supported distribution recommends handicap home, including -2',()=>{const a=analyze(largeWin,{'1':.71,X:.19,'2':.1},-2);assert.equal(a.tipCode,'1');near(a.probabilities['1'],.55);});
test('home win is not blindly mapped to handicap draw',()=>{const a=analyze(smallWin,{'1':.51,X:.30,'2':.19});assert.equal(a.primaryTipCode,'1');assert.equal(a.tipCode,'2');near(a.probabilities['2'],.49);});
test('conditional win-shape does not replace unconditional hit probabilities',()=>{const a=analyze(smallWin,{'1':.64,X:.2,'2':.16});near(a.conditionalOnPrimary.X,.46/.64);assert.ok(a.conditionalOnPrimary.X>a.probabilities.X);near(a.conditionalOnPrimary['2'],0);});
test('published HAD mass is preserved under different raw score model',()=>{const p={'1':.80,X:.12,'2':.08};const a=analyze(smallWin,p);for(const c of ['1','X','2'])near(a.marginDistribution.filter(r=>(r.margin>0?'1':r.margin<0?'2':'X')===c).reduce((s,r)=>s+r.probability,0),p[c]);});
test('partial top score lists cannot be normalized as a complete distribution',()=>assert.throws(()=>analyze(smallWin.slice(0,2),{'1':.64,X:.2,'2':.16}),/Incomplete/));
test('duplicate, null, negative and NaN score cells rejected',()=>{assert.throws(()=>analyze([...smallWin,smallWin[0]],{'1':.64,X:.2,'2':.16}),/Duplicate/);for(const p of [null,-1,NaN])assert.throws(()=>analyze([{home:1,away:0,probability:p}],{'1':1,X:0,'2':0}));});
test('missing expected-goal parameters never become zero',()=>{for(const v of [null,undefined,'',true])assert.throws(()=>analyzeHandicap({line:-1,hadProbabilities:{'1':.6,X:.2,'2':.2},homeLambda:v,awayLambda:1}));});
test('no arbitrary handicap tip on an exact probability tie',()=>{const rows=[{home:1,away:0,probability:.4},{home:2,away:0,probability:.4},{home:0,away:0,probability:.2}];assert.equal(analyze(rows,{'1':.8,X:.2,'2':0}).tipCode,null);});
test('adaptive score tail retains goals above five',()=>{const shape=poissonShape(7,1);assert.ok(shape.rows.some(r=>r.home>5&&r.probability>1e-3));assert.ok(shape.tailBound<1e-12);});
test('positive/negative handicap distributions mirror under swapped teams',()=>{const rows=largeWin.map(r=>({home:r.away,away:r.home,probability:r.probability}));const a=analyze(largeWin,{'1':.71,X:.19,'2':.1},-2),b=analyze(rows,{'1':.1,X:.19,'2':.71},2);near(a.probabilities['1'],b.probabilities['2']);near(a.probabilities.X,b.probabilities.X);});
test('probabilities sum to one for a grid of rates and signed integer lines',()=>{for(const h of [.1,1,3,7])for(const a of [.1,1,3])for(const line of [-3,-2,-1,0,1,2,3]){const x=analyzeHandicap({line,homeLambda:h,awayLambda:a,hadProbabilities:{'1':.56,X:.25,'2':.19}});near(Object.values(x.probabilities).reduce((s,v)=>s+v,0),1);assert.ok(x.projectedTailBound<=1e-8);}});
test('actual decision carries model-generated handicap analysis',()=>{const d=decision(fixture());assert.equal(d.handicapAnalysis.status,'ready');assert.equal(d.handicapAnalysis.line,-1);assert.ok(validDecision(d));assert.equal(d.handicapAnalysis.odds,null);assert.equal(d.handicapAnalysis.comboEligible,false);});
test('adding handicap analysis never changes ordinary HAD direction or SP',()=>{const plain=decision(match()),d=decision(fixture());assert.equal(d.tipCode,plain.tipCode);assert.deepEqual(d.probabilities,plain.probabilities);assert.equal(d.odds,plain.odds);});
test('changing only line or goal shape creates a new immutable decision id',()=>{const a=decision(fixture()),m=fixture();m.handicapLine='-2';m.probabilityModel.handicap.line='-2';const b=decision(m);assert.notEqual(a.decisionId,b.decisionId);const n=fixture();n.probabilityModel.calculationTrace.poisson.lambdas.home=3;assert.notEqual(a.decisionId,decision(n).decisionId);});
test('same goal inputs and line remain idempotent',()=>assert.equal(decision(fixture()).decisionId,decision(fixture()).decisionId));
test('old decisions have no retrospective handicap forecast',()=>{const d=decision(match());assert.equal(d.handicapAnalysis,undefined);assert.ok(validDecision(d));});
test('missing, stale or conflicting handicap data does not suppress HAD',()=>{for(const mode of ['missing','stale','conflict']){const m=fixture();if(mode==='missing')delete m.probabilityModel.calculationTrace;if(mode==='stale')m.handicapOddsUpdatedAt=new Date(NOW-16*60000).toISOString();if(mode==='conflict')m.probabilityModel.handicap.line='+1';const d=decision(m);assert.ok(validDecision(d));assert.equal(d.handicapAnalysis.status,'unavailable');}});
test('current-cycle adapter carries shape without borrowing parent frozen inputs',()=>{const fresh=fixture(),old=structuredClone(fresh);old.probabilityModel.calculationTrace.poisson.lambdas.home=7;const [x]=attachProspectiveForecastInputs([old],[fresh],NOW);assert.equal(x.prospectiveForecastInput.probabilityModel.calculationTrace.poisson.lambdas.home,1.8);assert.equal(decision(x).handicapAnalysis.snapshot.homeLambda,1.8);const missing=fixture();delete missing.probabilityModel.calculationTrace;const[y]=attachProspectiveForecastInputs([old],[missing],NOW);assert.equal(decision(y).handicapAnalysis.status,'unavailable');});
test('a changed stored handicap probability invalidates the saved decision',()=>{const d=structuredClone(decision(fixture()));d.handicapAnalysis.probabilities.X=.99;assert.equal(validDecision(d),false);});
test('HAD combinations still use the original market, odds and primary code',()=>{const ds=[1,2,3].map(id=>decision(fixture(id)));for(const size of [2,3]){const c=chooseCombo(ds,size,NOW);assert.ok(c);assert.ok(c.legs.every(l=>l.market==='HAD'&&l.odds===1.8&&l.tipCode==='1'));}});
test('handicap settlement uses the stored signed line and the same official event',()=>{const d=decision(fixture()),row={...fixture(),status:'FINISHED',testOfficial:true,scoreHome:1,scoreAway:0};const e=collectResults([row],new Map(),validators,NOW+9*3600000).updates[0];const s=settleDecision(d,e);assert.equal(s.state,'WON');assert.equal(s.handicap.actual,'X');assert.equal(s.handicap.line,-1);assert.equal(s.handicap.state,d.handicapAnalysis.tipCode==='X'?'WON':'LOST');});
test('official correction updates handicap review without changing frozen analysis',()=>{const d=decision(fixture()),copy=structuredClone(d),row={...fixture(),status:'FINISHED',testOfficial:true,scoreHome:1,scoreAway:0};const e=collectResults([row],new Map(),validators,NOW+9*3600000).updates[0];const next=collectResults([{...row,scoreHome:3,resultRevision:1}],new Map([[key(row),e]]),validators,NOW+10*3600000).updates[0];assert.equal(settleDecision(d,e).handicap.actual,'X');assert.equal(settleDecision(d,next).handicap.actual,'1');assert.deepEqual(d,copy);});
test('pending and VOID results keep handicap review unscored',()=>{const d=decision(fixture());assert.equal(settleDecision(d).handicap.state,'PENDING');const row={...fixture(),testOfficial:true,resultDisposition:'VOID'};const e=collectResults([row],new Map(),validators,NOW).updates[0];assert.equal(settleDecision(d,e).handicap.state,'VOID');});
test('publish -> combo -> view keeps the handicap snapshot through the actual runtime',async()=>{const p=memoryPorts();p.current=[1,2,3].map(id=>fixture(id));const result=await createRuntime(p,{validators}).publishingCycle();assert.ok(result.publication.ok);assert.ok(result.combinations.ok);assert.equal(p.state.view.current.length,3);assert.equal(p.state.view.current[0].decision.handicapAnalysis.status,'ready');assert.equal(p.state.view.previews.length,2);});
