'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {makeDecision,validDecision,evaluateCurrent,chooseCombo,freezeCombo,product}=require('../scripts/recommendationPlatform/decision.cjs');
const {collectResults,key,settleDecision,settleCombo,summary}=require('../scripts/recommendationPlatform/results.cjs');
const {createRuntime}=require('../scripts/recommendationPlatform/runtime.cjs');
const {NOW,match,publication,validators,memoryPorts}=require('./recommendationFixture.cjs');
const decision=(id=1,patch={},now=NOW)=>makeDecision(match(id,now,patch),{now,publication:publication(now)}).decision;
const all=(now=NOW)=>[1,2,3].map(id=>decision(id,{},now));
const official=(id,home,away,rev=0)=>({...match(id),status:'FINISHED',testOfficial:true,scoreHome:home,scoreAway:away,resultRevision:rev});

test('no formal single recommendations still produces auditable decisions and both combos',()=>{const ds=all();assert.ok(ds.every(validDecision));assert.ok(chooseCombo(ds,2,NOW));assert.ok(chooseCombo(ds,3,NOW));});
test('single and combo reference exactly the same direction vector and ID',()=>{const ds=all(),c=chooseCombo(ds,3,NOW);for(const leg of c.legs)assert.deepEqual(leg,ds.find(d=>d.decisionId===leg.decisionId));});
test('minimum SP does not determine direction or ban high-SP legs',()=>{const m=match();m.probabilityModel.oneXTwo.final={home:20,draw:30,away:50};const d=makeDecision(m,{now:NOW,publication:publication(NOW)}).decision;assert.equal(d.tipCode,'2');assert.equal(d.odds,4.5);});
test('metadata confidence and reference labels cannot change the chosen outcome',()=>{assert.deepEqual(decision(),decision(1,{predictions:[],trustScore:0,modelRiskStable:false}));});
test('immutable decision retains full input and rejects changes',()=>{const d=decision();assert.throws(()=>d.probabilities['1']=.9);assert.equal(validDecision({...d,tipCode:'2'}),false);});
test('input changes append another ID without mutating the old one',()=>{const a=decision(),copy=JSON.stringify(a),b=decision(1,{odds:{odds1:1.9,oddsX:3.5,odds2:4.5}});assert.notEqual(a.decisionId,b.decisionId);assert.equal(JSON.stringify(a),copy);});
test('unchanged input across rereads keeps the same decision ID',()=>{const m=match(),a=makeDecision(m,{now:NOW,publication:publication(NOW)}).decision,b=makeDecision(m,{now:NOW+1000,publication:publication(NOW+1000)}).decision;assert.equal(a.decisionId,b.decisionId);});
test('null probabilities and tied directions never create invented predictions',()=>{for(const p of [{home:null,draw:40,away:60},{home:40,draw:40,away:20}]){const m=match();m.probabilityModel.oneXTwo.final=p;assert.equal(makeDecision(m,{now:NOW,publication:publication(NOW)}).decision,null);}});
test('stale, future and foreign-provider SP are excluded',()=>{for(const p of [{oddsUpdatedAt:'2026-09-17T09:00:00Z'},{oddsUpdatedAt:'2026-09-17T11:00:00Z'},{oddsSource:'500.com:had'}])assert.equal(decision(1,p),null);});
test('invalid precision cannot round a combination over the floor',()=>{assert.equal(decision(1,{odds:{odds1:1.80001,oddsX:3.5,odds2:4.5}}),null);assert.equal(product([{odds:1.58},{odds:1.58}]).passes(2.5),false);assert.equal(product([{odds:1.25},{odds:2}]).passes(2.5),true);});
test('three-leg SP floor is checked before display rounding',()=>{assert.equal(product([{odds:1.7},{odds:1.7},{odds:1.73}]).passes(5),false);assert.equal(product([{odds:1.25},{odds:2},{odds:2}]).passes(5),true);});
test('suspension, void, started game and hard cutoff reject new decisions',()=>{for(const patch of [{status:'LIVE'},{isOnSale:false},{saleStatus:'SUSPENDED'},{resultDisposition:'VOID'},{buyEndTime:'2026-09-17T10:00:00Z'}])assert.equal(decision(1,patch),null);});
test('duplicates and conflicting event identities cannot inflate selections',()=>{const r=evaluateCurrent([match(),match(),match(2),match(2,NOW,{homeTeamId:'conflict'})],{now:NOW,publication:publication(NOW)});assert.equal(r.decisions.length,1);});
test('same event and shared team cannot appear twice',()=>{assert.equal(chooseCombo([decision(),decision()],2,NOW),null);assert.equal(chooseCombo([decision(),decision(2,{awayTeamId:'h1'})],2,NOW),null);});
test('all games in same league may qualify without made-up risk deductions',()=>assert.ok(chooseCombo(all(),3,NOW)));
test('publication clock crossing midnight cannot reset the original cutoff',()=>{assert.equal(makeDecision(match(),{now:Date.parse('2026-09-17T16:01:00Z'),publication:publication(NOW)}).decision,null);});
test('early freeze preserves an earlier kickoff rather than waiting for the night',()=>{const now=Date.parse('2026-09-17T11:00:00Z'),ds=[1,2].map(id=>decision(id,{buyEndTime:'2026-09-17T11:04:00Z'},now)),c=chooseCombo(ds,2,now);assert.ok(freezeCombo(c,now));});
test('stale preview or post-cutoff preview cannot freeze',()=>{const c=chooseCombo(all(),2,NOW);assert.equal(freezeCombo(c,NOW+3*3600000),null);assert.equal(freezeCombo(c,Date.parse('2026-09-17T14:00:00Z')),null);});
test('original single and combo decisions remain immutable after result correction',()=>{const ds=all(),before=JSON.stringify(ds),c=chooseCombo(ds,3,NOW);const first=collectResults([1,2,3].map(id=>official(id,2,0)),new Map(),validators,NOW+9*3600000);const heads=new Map(first.updates.map(e=>[e.eventKey,e]));assert.equal(settleDecision(ds[0],heads.get(key(ds[0]))).state,'WON');assert.equal(settleCombo(c,heads).state,'WON');const corrected=collectResults([official(1,0,2,1)],heads,validators,NOW+10*3600000);heads.set(corrected.updates[0].eventKey,corrected.updates[0]);assert.equal(settleDecision(ds[0],heads.get(key(ds[0]))).state,'LOST');assert.equal(settleCombo(c,heads).state,'LOST');assert.equal(JSON.stringify(ds),before);});
test('same-revision conflicting results stay disputed even when one row disappears',()=>{const initial=collectResults([official(1,2,0),official(1,0,2)],new Map(),validators,NOW+9*3600000);assert.equal(initial.updates[0].state,'DISPUTED');const heads=new Map(initial.updates.map(e=>[e.eventKey,e]));const repeat=collectResults([official(1,2,0)],heads,validators,NOW+10*3600000);assert.equal(repeat.updates.length,0);});
test('higher official revision may resolve a dispute',()=>{const first=collectResults([official(1,2,0),official(1,0,2)],new Map(),validators,NOW+9*3600000);const next=collectResults([official(1,2,0,2)],new Map(first.updates.map(e=>[e.eventKey,e])),validators,NOW+10*3600000);assert.equal(next.updates[0].state,'FINAL');});
test('late lower revision cannot revert newer official correction',()=>{const first=collectResults([official(1,2,0,2)],new Map(),validators,NOW+9*3600000);assert.equal(collectResults([official(1,0,2,1)],new Map(first.updates.map(e=>[e.eventKey,e])),validators,NOW+10*3600000).updates.length,0);});
test('repeated identical result does not grow the event log',()=>{const first=collectResults([official(1,2,0)],new Map(),validators,NOW+9*3600000);assert.equal(collectResults([official(1,2,0),official(1,2,0)],new Map(first.updates.map(e=>[e.eventKey,e])),validators,NOW+10*3600000).updates.length,0);});
test('untrusted or future result cannot settle a match',()=>{assert.equal(collectResults([{...official(1,2,0),testOfficial:false}],new Map(),validators,NOW+9*3600000).updates.length,0);assert.equal(collectResults([official(1,2,0)],new Map(),validators,NOW).updates.length,0);});
test('official cancellation may be recorded before kickoff',()=>{const r=collectResults([{...match(),testOfficial:true,resultDisposition:'VOID'}],new Map(),validators,NOW);assert.equal(r.updates[0].state,'VOID');assert.equal(settleDecision(decision(),r.updates[0]).state,'VOID');});
test('wrong team identity cannot silently bind a final to a decision',()=>{const r=collectResults([{...official(1,2,0),homeTeamId:'other'}],new Map(),validators,NOW+9*3600000);assert.equal(settleDecision(decision(),r.updates[0]).state,'DISPUTED');});
test('pending, void and disputed are excluded from hit-rate denominator',()=>{const s=summary([{settlement:{state:'WON'}},{settlement:{state:'LOST'}},{settlement:{state:'PENDING'}},{settlement:{state:'VOID'}},{settlement:{state:'DISPUTED'}}]);assert.equal(s.hitRate,.5);assert.equal(s.settled,2);assert.equal(summary([]).hitRate,null);});
test('Brier uses the stored full vector, not current recomputed probabilities',()=>{const d=decision(),s=summary([{decision:d,settlement:{state:'WON',actual:'1'}}],true);assert.ok(Math.abs(s.brier-(.45**2+.25**2+.2**2))<1e-12);});
test('publish performs no history reads',async()=>{const ports=memoryPorts(),runtime=createRuntime(ports,{validators});assert.equal((await runtime.publish()).ok,true);assert.equal(ports.calls.some(([m])=>m==='history'),false);assert.equal(ports.state.decisions.length,3);});
test('an invalid current item does not prevent valid events publishing',async()=>{const p=memoryPorts();p.current=[null,match(1),match(2)];const r=createRuntime(p,{validators});await r.publish();assert.equal(p.state.decisions.length,2);assert.ok(p.state.issues.length>0);});
test('one write failure is isolated with a savepoint',async()=>{const p=memoryPorts();p.faults.add('match:2');const r=createRuntime(p,{validators});assert.equal((await r.publish()).ok,true);assert.equal(p.state.decisions.length,2);});
test('settlement failure cannot roll back new publications or stop view advancement',async()=>{const p=memoryPorts(),r=createRuntime(p,{validators});await r.publishingCycle();const before=p.state.decisions.length;p.faults.add('history');const s=await r.settlementCycle();assert.equal(s.settlement.ok,false);assert.equal(p.state.decisions.length,before);assert.equal(p.state.view.current.length,3);assert.equal(p.state.view.lanes.settlement.status,'error');});
test('combo failure does not roll back single publications',async()=>{const p=memoryPorts();p.now=Date.parse('2026-09-17T13:00:00Z');p.current=[1,2,3].map(id=>match(id,p.now));p.faults.add('insertCombo');const r=createRuntime(p,{validators});const out=await r.publishingCycle();assert.equal(out.combinations.ok,false);assert.equal(p.state.decisions.length,3);assert.equal(p.state.view.current.length,3);});
test('view failure retains its last snapshot while new publication still commits',async()=>{const p=memoryPorts(),r=createRuntime(p,{validators});await r.publishingCycle();const original=structuredClone(p.state.view);p.current=[match(4)];p.faults.add('saveView');await r.publishingCycle();assert.equal(p.state.decisions.length,4);assert.deepEqual(p.state.view,original);});
test('same-input retry is idempotent',async()=>{const p=memoryPorts(),r=createRuntime(p,{validators});await r.publishingCycle();await r.publishingCycle();assert.equal(p.state.decisions.length,3);});
test('all frozen combo IDs refer to committed decision rows',async()=>{const p=memoryPorts();p.now=Date.parse('2026-09-17T13:00:00Z');p.current=[1,2,3].map(id=>match(id,p.now));const r=createRuntime(p,{validators});await r.publishingCycle();assert.equal(p.state.combos.length,2);for(const c of p.state.combos)for(const leg of c.legs)assert.deepEqual(leg,p.state.decisions.find(d=>d.decisionId===leg.decisionId));});
test('rerun cannot rewrite frozen combos even when input changes',async()=>{const p=memoryPorts();p.now=Date.parse('2026-09-17T13:00:00Z');p.current=[1,2,3].map(id=>match(id,p.now));const r=createRuntime(p,{validators});await r.publishingCycle();const frozen=structuredClone(p.state.combos);p.now+=60000;p.current=[4,5,6].map(id=>match(id,p.now));await r.publishingCycle();assert.deepEqual(p.state.combos,frozen);});
test('official correction changes both single and combo view without modifying frozen rows',async()=>{const p=memoryPorts();p.now=Date.parse('2026-09-17T13:00:00Z');p.current=[1,2,3].map(id=>match(id,p.now));const r=createRuntime(p,{validators});await r.publishingCycle();const original=structuredClone({decisions:p.state.decisions,combos:p.state.combos});p.now=Date.parse('2026-09-17T19:00:00Z');p.history=[1,2,3].map(id=>official(id,2,0));await r.settlementCycle();assert.equal(p.state.view.review.statistics.single.won,3);assert.equal(p.state.view.review.statistics.three.won,1);p.history=[official(1,0,2,2)];await r.settlementCycle();assert.equal(p.state.view.review.statistics.single.lost,1);assert.equal(p.state.view.review.statistics.three.lost,1);assert.deepEqual(p.state.decisions,original.decisions);assert.deepEqual(p.state.combos,original.combos);});
test('latest decision per event is counted once, not every revision',async()=>{const p=memoryPorts(),r=createRuntime(p,{validators});await r.publishingCycle();p.now+=60000;p.current=[1,2,3].map(id=>match(id,p.now,{odds:{odds1:1.9,oddsX:3.5,odds2:4.5}}));await r.publishingCycle();assert.equal(p.state.decisions.length,6);assert.equal(p.state.view.review.statistics.single.published,3);});
test('optimized enumeration agrees with exhaustive search on deterministic randomized samples',()=>{
  let seed=2917;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  for(let trial=0;trial<80;trial++){
    const n=5+Math.floor(random()*5),ds=Array.from({length:n},(_,i)=>{const probability=.36+random()*.4;const m=match(i+1);m.probabilityModel.oneXTwo.final={home:probability,draw:(1-probability)/2,away:(1-probability)/2};m.odds.odds1=Number((1.1+random()*2.7).toFixed(2));return makeDecision(m,{now:NOW,publication:publication(NOW)}).decision;});
    for(const size of [2,3]){
      let max=-Infinity;const walk=(at,legs)=>{if(legs.length===size){if(product(legs).passes(size===2?2.5:5))max=Math.max(max,legs.reduce((v,d)=>v+Math.log(d.modelProbability),0));return;}for(let i=at;i<ds.length;i++)walk(i+1,[...legs,ds[i]]);};walk(0,[]);
      const selected=chooseCombo(ds,size,NOW);if(!Number.isFinite(max))assert.equal(selected,null);else assert.ok(Math.abs(selected.legs.reduce((v,d)=>v+Math.log(d.modelProbability),0)-max)<1e-10);
    }
  }
});
test('settlement can progress even while current-source publication is unavailable',async()=>{const p=memoryPorts(),r=createRuntime(p,{validators});await r.publishingCycle();p.now=Date.parse('2026-09-17T19:00:00Z');p.history=[official(1,2,0)];p.faults.add('publication');const result=await r.settlementCycle();assert.equal(result.settlement.ok,true);assert.equal(p.state.view.review.statistics.single.won,1);});
