import { useState } from 'react';
import { ArrowRight, Clock, Heart, KeyRound, LogOut, ShieldCheck, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAccount } from '../context/AccountContext';
import { useApp } from '../context/AppContextCore';
import { formatAccessCode } from '../services/accessControl';
import '../styles/account.css';

export function Account(){
  const account=useAccount(),{language,clearAccessSession}=useApp(),navigate=useNavigate(),zh=language==='zh';
  const [code,setCode]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function perform(action:string,fn:()=>Promise<unknown>,success:string){setBusy(action);setError('');setNotice('');try{const result=await fn();setNotice(typeof result==='number'?(zh?`已退出其他 ${result} 个登录会话。`:`Signed out ${result} other sessions.`):success);if(action==='redeem')setCode('');}catch(cause){setError(cause instanceof Error?cause.message:'操作未完成。');}finally{setBusy('');}}
  if(account.loading)return <div className="account-page"><div className="account-empty" role="status">{zh?'正在读取账号…':'Loading your account…'}</div></div>;
  if(!account.user)return <div className="account-page"><section className="account-card account-welcome"><UserRound size={32}/><h1>{zh?'我的账号':'Your account'}</h1><p>{zh?'登录后保存关注，查看自己的赛后复盘。':'Sign in to follow matches and review their results.'}</p>{account.sessionError&&<p className="account-error" role="alert">{account.sessionError}</p>}<Link className="account-primary" to="/auth?returnTo=%2Faccount">{zh?'登录 / 注册':'Sign in / Register'}<ArrowRight size={16}/></Link><Link className="account-text-link" to="/fixtures">{zh?'先看看赛程':'Browse fixtures'}</Link></section></div>;
  const expiry=account.access.expiresAt&&Number.isFinite(Date.parse(account.access.expiresAt))?new Date(account.access.expiresAt).toLocaleString(zh?'zh-CN':'en-GB',{timeZone:'Asia/Shanghai',hour12:false}):null;
  const label=account.access.active?(account.access.kind==='trial'?(zh?'体验中':'Trial active'):account.access.kind==='legacy-code'?(zh?'访问码权益有效':'Access-code benefits active'):(zh?'内容权益有效':'Content access active')):(zh?'普通账号':'Free account');
  return <div className="account-page"><header className="account-heading"><span className="account-eyebrow">{zh?'我的':'ACCOUNT'}</span><h1>{zh?'你好，':'Hello, '}{account.user.displayName||account.user.username}</h1><p>{zh?'在这里管理内容权限和个人关注。':'Manage your content access and followed matches.'}</p></header>
    {error&&<p className="account-error" role="alert">{error}</p>}{notice&&<p className="account-success" role="status">{notice}</p>}{account.sessionError&&<p className="account-error" role="alert">{account.sessionError}</p>}
    {(account.user.role==='operator'||account.user.role==='admin')&&<p><Link className="account-secondary" to="/account-admin">{zh?'体验管理后台':'Account administration'}</Link></p>}
    <div className="account-grid"><section className="account-card"><div className="account-card-title"><ShieldCheck size={22}/><h2>{zh?'内容权限':'Content access'}</h2><span className={`account-pill${account.access.active?' is-active':''}`}>{label}</span></div><p>{zh?'账号长期保留。内容权益到期后，仍可管理关注和查看已保存的复盘。':'Your account and followed records remain available after content access expires.'}</p>{expiry&&<p className="account-expiry"><Clock size={16}/>{zh?'权益截止（北京时间）：':'Access ends (Beijing): '}{expiry}</p>}
      {account.access.trialAvailable?<div className="account-trial"><strong>{zh?'领取 3 天体验':'Claim a 3-day trial'}</strong><p>{zh?'点击领取后开始计时；每个账号可领取一次，不自动续费。':'Starts when claimed. Once per account, with no automatic renewal.'}</p><button type="button" className="account-primary" disabled={Boolean(busy)} onClick={()=>perform('trial',account.claimTrial,zh?'3 天体验已启用。':'Your 3-day trial is active.')}>{busy==='trial'?(zh?'领取中…':'Activating…'):(zh?'主动领取体验':'Activate trial')}</button></div>:<p className="account-muted">{account.access.active?(zh?'当前内容权限已生效。':'Your content access is active.'):(zh?'当前没有有效内容权益；可使用已有访问码兑换。':'No active content access. Redeem an existing access code below.')}</p>}
      <p className="account-note">{zh?'参考／影子推荐仍在验证中，开通内容权限不会改变模型等级或提高已公布的命中率。':'Model validation is ongoing. Access benefits do not change the model status or historical hit rate.'}</p></section>
      <section className="account-card"><div className="account-card-title"><Heart size={22}/><h2>{zh?'我的关注':'Following'}</h2></div><p>{zh?'从赛程或推荐卡关注比赛，赛后查看当时记录和真实结果。':'Follow from a fixture or pick, then compare the saved record with its actual result.'}</p><Link className="account-primary" to="/following">{zh?'查看我的关注':'View following'}<ArrowRight size={16}/></Link><p className="account-muted">{zh?'普通账号也可使用，不需要领取体验。':'Available on a free account; no trial required.'}</p></section>
      <section className="account-card"><div className="account-card-title"><KeyRound size={22}/><h2>{zh?'兑换已有访问码':'Redeem an access code'}</h2></div><p>{zh?'把尚有效的原访问码权益绑定到当前账号。有效期以服务端核验结果为准。':'Bind the remaining access-code benefits to your account. The server verifies its expiry.'}</p><form className="account-form" onSubmit={event=>{event.preventDefault();if(code.trim())void perform('redeem',()=>account.redeemCode(code),zh?'访问码已兑换，权益已更新。':'Code redeemed. Access updated.');}}><label htmlFor="account-code">{zh?'访问码':'Access code'}</label><input id="account-code" value={code} onChange={event=>setCode(formatAccessCode(event.target.value))} placeholder="XXXX-XXXX-XXXX" autoComplete="off"/><button type="submit" className="account-secondary" disabled={Boolean(busy)||!code.trim()}>{busy==='redeem'?(zh?'兑换中…':'Redeeming…'):(zh?'兑换到此账号':'Redeem to this account')}</button></form></section>
      <section className="account-card"><div className="account-card-title"><UserRound size={22}/><h2>{zh?'登录管理':'Sign-in management'}</h2></div><dl className="account-facts"><dt>{zh?'账号':'Username'}</dt><dd>{account.user.username}</dd></dl><p>{zh?'退出其他设备后，当前设备仍保持登录。':'Signing out other devices keeps this device signed in.'}</p><div className="account-action-stack"><button className="account-secondary" disabled={Boolean(busy)} onClick={()=>perform('sessions',account.revokeOtherSessions,'')}>{busy==='sessions'?(zh?'正在处理…':'Working…'):(zh?'退出其他设备':'Sign out other devices')}</button><button className="account-text-link account-danger" disabled={Boolean(busy)} onClick={()=>perform('logout',async()=>{await account.logout();clearAccessSession();navigate('/auth',{replace:true});},'')}><LogOut size={16}/>{zh?'退出当前账号':'Sign out'}</button></div></section></div>
  </div>;
}
