import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Heart, RefreshCw, Search } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAccount } from '../context/AccountContext';
import { useApp } from '../context/AppContextCore';
import { filterFollowing, followGroup } from '../services/accountApi';
import type { FollowRow } from '../services/accountApi';
import '../styles/account.css';

export function Following(){
  const account=useAccount(),{language}=useApp(),zh=language==='zh';
  const [params,setParams]=useSearchParams();
  const query=params.get('q')||'',group=['upcoming','pending','settled'].includes(params.get('tab')||'')?params.get('tab')!:'all';
  const updateFilters=(next:{q?:string;tab?:string})=>{const search=new URLSearchParams(params);for(const [key,value] of Object.entries(next)){if(value&&value!=='all')search.set(key,value);else search.delete(key);}setParams(search,{replace:true});};
  const [limit,setLimit]=useState(12),[busy,setBusy]=useState(''),[error,setError]=useState(''),[removed,setRemoved]=useState<FollowRow|null>(null),[now,setNow]=useState(Date.now());
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{
    if(!account.user)return;
    const refresh=()=>{if(document.visibilityState!=='hidden')void account.refreshFollowing();};
    refresh();
    const timer=window.setInterval(refresh,60000);
    window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);
    return()=>{window.clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};
  },[account.user?.id,account.refreshFollowing]);
  const filtered=useMemo(()=>filterFollowing(account.following,query,group,now),[account.following,query,group,now]);
  const format=(value:string|undefined)=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString(zh?'zh-CN':'en-GB',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Shanghai'}):'—';
  const groups=[['all',zh?'全部':'All'],['upcoming',zh?'未赛':'Upcoming'],['pending',zh?'待结果':'Awaiting result'],['settled',zh?'已结算':'Settled']];
  async function remove(row:FollowRow){setBusy(row.id);setError('');try{await account.unfollowMatch(row.id);setRemoved(row);}catch(cause){setError(cause instanceof Error?cause.message:'取消关注未完成。');}finally{setBusy('');}}
  async function undo(){if(!removed)return;setBusy('undo');setError('');try{await account.followMatch(removed.matchId,removed.decision?.decisionId);setRemoved(null);}catch(cause){setError(cause instanceof Error?cause.message:'恢复关注未完成。');}finally{setBusy('');}}
  if(account.loading)return <div className="account-page"><p className="account-empty" role="status">{zh?'正在读取账号…':'Loading your account…'}</p></div>;
  if(!account.user)return <div className="account-page"><section className="account-card account-welcome"><Heart size={32}/><h1>{zh?'把关心的比赛留在这里':'Keep the matches you care about'}</h1><p>{zh?'登录后跨设备保存关注，赛后查看真实赛果。':'Sign in to save matches across devices and review actual results.'}</p><Link className="account-primary" to={`/auth?returnTo=${encodeURIComponent('/following'+(params.toString()?'?'+params.toString():''))}`}>{zh?'登录 / 注册':'Sign in / Register'}<ArrowRight size={16}/></Link></section></div>;
  return <div className="account-page following-page"><header className="account-heading account-heading-row"><div><span className="account-eyebrow">{zh?'我的比赛':'MY MATCHES'}</span><h1>{zh?'我的关注':'Following'}</h1><p>{zh?'关注时的记录与赛后结果分别保留，未结算不会记为未命中。':'Saved records and official results are shown separately. Pending is not a loss.'}</p></div><button type="button" className="account-secondary" onClick={()=>account.refreshFollowing()} disabled={account.followingLoading}><RefreshCw size={16}/>{account.followingLoading?(zh?'更新中':'Updating'):(zh?'刷新':'Refresh')}</button></header>
    {account.followingError&&<div className="account-error" role="alert"><span>{account.followingError}</span><button type="button" onClick={()=>account.refreshFollowing()} disabled={account.followingLoading}>{zh?'重新读取':'Retry'}</button></div>}{error&&<p className="account-error" role="alert">{error}</p>}{removed&&<div className="account-success" role="status"><span>{zh?'已取消关注：':'Unfollowed: '}{removed.homeTeamName} · {removed.awayTeamName}</span><button type="button" disabled={Boolean(busy)} onClick={undo}>{zh?'撤销':'Undo'}</button></div>}
    <section className="account-card following-toolbar"><div className="account-tabs" role="group" aria-label={zh?'比赛状态':'Match status'}>{groups.map(([key,label])=><button type="button" key={key} aria-pressed={group===key} onClick={()=>{updateFilters({tab:key});setLimit(12);}}>{label}<small>{key==='all'?account.following.length:account.following.filter(row=>followGroup(row,now)===key).length}</small></button>)}</div><label className="account-search"><Search size={18}/><span className="account-sr-only">{zh?'搜索球队':'Search teams'}</span><input type="search" value={query} onChange={event=>{updateFilters({q:event.target.value});setLimit(12);}} placeholder={zh?'搜索球队或比赛编号':'Search team or fixture number'}/></label></section>
    {account.followingLoading&&!account.following.length?<p className="account-empty" role="status">{zh?'正在读取我的关注…':'Loading followed matches…'}</p>:!filtered.length?<section className="account-card account-welcome"><Heart size={30}/><h2>{account.followingError?(zh?'关注列表暂时无法读取':'Following is unavailable'):query||group!=='all'?(zh?'没有符合条件的比赛':'No matching matches'):(zh?'还没有关注比赛':'No followed matches yet')}</h2><p>{query||group!=='all'?(zh?'试试其他球队，或恢复全部比赛。':'Try another team or show all matches.'):(zh?'在赛程或推荐卡点击“关注比赛”，这里就会保留你的选择。':'Choose Follow match from a fixture or pick to keep it here.')}</p>{query||group!=='all'?<button className="account-secondary" onClick={()=>{updateFilters({q:'',tab:'all'});setLimit(12);}}>{zh?'清除筛选':'Clear filters'}</button>:<Link className="account-primary" to="/fixtures">{zh?'去看今日赛程':'Browse fixtures'}<ArrowRight size={16}/></Link>}</section>:<div className="following-list">{filtered.slice(0,limit).map(row=>{
      const state=row.result?.state,settled=followGroup(row,now)==='settled',decision=row.decision;
      const resultLabel=state==='WON'&&decision?(zh?'命中':'Won'):state==='LOST'&&decision?(zh?'未命中':'Lost'):state==='VOID'?(zh?'已作废':'Void'):state==='DISPUTED'?(zh?'赛果待核':'Result disputed'):settled?(zh?'正式结果':'Official result'):(zh?'等待正式赛果':'Awaiting official result');
      const direction=decision?.tipCode==='1'?(zh?'主胜':'Home'):decision?.tipCode==='X'?(zh?'平局':'Draw'):decision?.tipCode==='2'?(zh?'客胜':'Away'):zh?'未提供':'Unavailable';
      return <article className="account-card following-match" key={row.id}><header><span>{format(row.kickoffTime)} {zh?'北京':'Beijing'}</span><span className={`account-pill${settled?' is-active':''}`}>{groups.find(([key])=>key===followGroup(row,now))?.[1]}</span></header><h2><Link to={`/match/${encodeURIComponent(row.matchId)}`}>{row.homeTeamName}<span> vs </span>{row.awayTeamName}</Link></h2><div className="following-comparison"><section><h3>{zh?'关注时记录':'Record when followed'}</h3>{decision?<><strong>{direction}{typeof decision.odds==='number'&&Number.isFinite(decision.odds)?` · SP ${decision.odds.toFixed(2)}`:''}</strong><p>{zh?'发布于 ':'Published '}{format(decision.publishedAt)}</p><details><summary>{zh?'查看记录版本':'Record version'}</summary><code>{decision.decisionId}</code></details></>:<><strong>{zh?'当时没有可保存的推荐':'No pick was available at the time'}</strong><p>{zh?'只关注比赛，不补写后来发布的方向。':'This follows the fixture without adding a later pick.'}</p></>}</section><section><h3>{zh?'当前正式结果':'Current official result'}</h3><strong className={state==='WON'&&decision?'is-won':state==='LOST'&&decision?'is-lost':''}>{resultLabel}</strong>{row.result?.score&&<p className="following-score">{row.result.score}</p>}{!decision&&row.result?.score&&<p>{zh?'仅展示比赛结果，不计个人命中。':'Fixture result only; no personal hit counted.'}</p>}{row.result?.source&&<p>{zh?'来源：':'Source: '}{row.result.source}</p>}{(row.result?.asOf||row.result?.updatedAt)&&<p>{zh?'核对于 ':'Checked '}{format(row.result.asOf||row.result.updatedAt)}</p>}</section></div><footer><Link className="account-text-link" to={`/match/${encodeURIComponent(row.matchId)}?tab=history`}>{zh?'查看比赛与复盘':'Match details & review'}<ArrowRight size={15}/></Link><button type="button" className="account-text-link account-muted" disabled={Boolean(busy)} onClick={()=>remove(row)}>{busy===row.id?(zh?'处理中…':'Working…'):(zh?'取消关注':'Unfollow')}</button></footer></article>;
    })}</div>}
    {filtered.length>limit&&<div className="account-load-more"><span>{zh?`已显示 ${Math.min(limit,filtered.length)} / ${filtered.length} 场`:`${Math.min(limit,filtered.length)} / ${filtered.length} shown`}</span><button className="account-secondary" onClick={()=>setLimit(value=>value+12)}>{zh?'再显示 12 场':'Show 12 more'}</button></div>}
  </div>;
}
