'use strict';
// Refresh verified public badge assets explicitly, never during a data cycle.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),folder=path.join(root,'src/assets/team-badges');
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
async function main(){
 const catalog=JSON.parse(fs.readFileSync(path.join(root,'src/services/teamCrestCatalog.json'),'utf8'));
 const visual=fs.readFileSync(path.join(root,'src/services/teamVisuals.ts'),'utf8');
 const flagTable=visual.slice(visual.indexOf('const FLAG_CODE_BY_NAME'),visual.indexOf('const FALLBACK_TEAM'));
 const codes=[...new Set([...flagTable.matchAll(/:\s*'([a-z]{2}(?:-[a-z]{3})?)'/g)].map(m=>m[1]))].sort();
 const requests=[...catalog.map(row=>({key:row.key,name:row.name,sourceUrl:row.sourceUrl,url:row.logoUrl,provider:row.provider})),...codes.map(code=>({key:'flag-'+code,name:code,sourceUrl:'https://flagpedia.net/download/api',url:'https://flagcdn.com/w80/'+code+'.png',provider:'flagpedia'}))];
 assert.equal(new Set(requests.map(r=>r.key)).size,requests.length);
 fs.mkdirSync(folder,{recursive:true});const manifestPath=path.join(folder,'manifest.json');
 const previous=fs.existsSync(manifestPath)?JSON.parse(fs.readFileSync(manifestPath,'utf8')).assets:[];
 const assets=[],failures=[];let cursor=0;
 async function one(item){
  assert(/^[a-z0-9-]+$/.test(item.key));const url=new URL(item.url);
  assert(url.protocol==='https:'&&['a.espncdn.com','flagcdn.com','www.kleague.com','myfc.co.jp'].includes(url.hostname),'Unverified image host '+url.hostname);
  const file=item.key+'.png',target=path.join(folder,file),old=previous.find(a=>a.key===item.key&&a.url===item.url);
  if(!process.argv.includes('--refresh')&&old&&fs.existsSync(target)&&sha(fs.readFileSync(target))===old.sha256){assets.push(old);return;}
  let error;
  for(let attempt=0;attempt<2;attempt++)try{
   const response=await fetch(item.url,{redirect:'error',signal:AbortSignal.timeout(15000)});
   assert.equal(response.status,200,item.key+' HTTP status');assert.match(response.headers.get('content-type')||'',/^image\/png(?:;|$)/i);
   assert(Number(response.headers.get('content-length')||0)<=2*1024*1024,'Image exceeds limit');
   const bytes=Buffer.from(await response.arrayBuffer());assert(bytes.length>=24&&bytes.length<=2*1024*1024);
   assert.equal(bytes.subarray(0,8).toString('hex'),'89504e470d0a1a0a','Not a PNG image');
   const width=bytes.readUInt32BE(16),height=bytes.readUInt32BE(20);assert(width>0&&height>0&&width<=2048&&height<=2048);
   fs.writeFileSync(target,bytes);assets.push({...item,file,sha256:sha(bytes),bytes:bytes.length,width,height,cachedAt:new Date().toISOString()});return;
  }catch(e){error=e;}
  failures.push({key:item.key,url:item.url,error:error.message});
 }
 await Promise.all(Array.from({length:5},async()=>{while(cursor<requests.length)await one(requests[cursor++]);}));
 assets.sort((a,b)=>a.key.localeCompare(b.key));
 fs.writeFileSync(manifestPath,JSON.stringify({version:1,assets},null,2)+'\n');
 const imports=assets.map((a,i)=>'import badge'+i+' from '+JSON.stringify('../assets/team-badges/'+a.file)+';').join('\n');
 fs.writeFileSync(path.join(root,'src/services/teamBadgeAssets.ts'),'// Generated by scripts/cacheTeamBadgeAssets.cjs; sources and hashes accompany the assets.\n'+imports+'\nexport const teamBadgeAssets: Record<string, string> = {\n'+assets.map((a,i)=>'  '+JSON.stringify(a.key)+': badge'+i+',').join('\n')+'\n};\n');
 const report={requested:requests.length,cached:assets.length,bytes:assets.reduce((n,a)=>n+a.bytes,0),failures};console.log(JSON.stringify(report));
 if(failures.length)process.exitCode=1;
}
main().catch(error=>{console.error(error.message);process.exitCode=1});
