'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {remote,environment}=require('./repairRemoteTransport.cjs');
const {verify,hash}=require('./foundationRepairPolicy.cjs');
const dir=path.resolve(process.argv[2]);
const bytes=fs.readFileSync(path.join(dir,'capsule.json')),sig=fs.readFileSync(path.join(dir,'capsule.sig'));
verify(bytes,sig,fs.readFileSync(environment().RELEASE_SIGNING_PUBLIC_KEY));
assert.equal(path.basename(dir),'capsule-'+hash(bytes));
const code=String.raw`const fs=require('node:fs'),crypto=require('node:crypto'),cp=require('node:child_process'),assert=require('node:assert/strict'),Module=require('node:module');
const bytes=Buffer.from(CAPSULE,'base64'),sig=Buffer.from(SIGNATURE,'base64'),key=fs.readFileSync('/etc/football-release/signing-public.pem');
assert.ok(crypto.verify('sha256',bytes,key,sig),'signature invalid');const p=JSON.parse(bytes);
const source=Buffer.from(p.policy.base64,'base64');assert.equal(crypto.createHash('sha256').update(source).digest('hex'),p.policy.sha256);
const m=new Module('/tmp/signed-foundation-policy.cjs');m._compile(source.toString('utf8'),m.id);m.exports.verify(bytes,sig,key);
const id=crypto.createHash('sha256').update(bytes).digest('hex'),parent='/var/lib/football-release/foundation-repairs',dir=parent+'/'+id;
assert.equal(fs.existsSync('/var/lib/football-release/recovery/current'),false);
if(!fs.existsSync(parent))fs.mkdirSync(parent,{mode:0o700});assert.equal(fs.realpathSync(parent),parent);
assert.equal(fs.statSync(parent).uid,0);assert.equal(fs.statSync(parent).mode&0o777,0o700);
assert.equal(fs.existsSync(dir),false,'capsule already staged; inspect original attempt');fs.mkdirSync(dir,{mode:0o700});
fs.writeFileSync(dir+'/capsule.json',bytes,{flag:'wx',mode:0o600});fs.writeFileSync(dir+'/capsule.sig',sig,{flag:'wx',mode:0o600});
fs.writeFileSync(dir+'/controller.cjs',Buffer.from(p.controller.base64,'base64'),{flag:'wx',mode:0o600});
fs.writeFileSync(dir+'/foundationRepairPolicy.cjs',source,{flag:'wx',mode:0o600});
const output=cp.execFileSync('/usr/bin/flock',['-n','/run/lock/football-release.lock','/opt/node-v22.22.1/bin/node',dir+'/controller.cjs','prepare',dir],{encoding:'utf8',timeout:540000,maxBuffer:4*1024**2});
console.log(output);`.replace('CAPSULE',JSON.stringify(bytes.toString('base64'))).replace('SIGNATURE',JSON.stringify(sig.toString('base64')));
const r=remote(code,{prefix:'foundation-preparation',timeout:570000});
console.log(JSON.stringify(r));if(r.exitCode!==0)process.exitCode=1;
