// 自动抓取真实比赛数据与 AI 预测生成脚本 (无需任何三方依赖，纯 Node.js 标准库)
const fs = require('fs');
const path = require('path');
const https = require('https');

// 封装 HTTPS Get 请求
function httpGet(url) {
  return new Promise((resolve, reject) => {
    https.get(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'application/json'
      }
    }, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(new Error(`Failed to parse JSON: ${e.message}`));
        }
      });
    }).on('error', (err) => {
      reject(err);
    });
  });
}

// 辅助函数，生成相对于今天的日期字符串 (YYYY-MM-DD)
function getDateStringOffset(offsetDays) {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
}

// 动态提取缩写，生成两字母队标
function getTeamLogoAbbr(teamName) {
  if (!teamName) return 'FC';
  // 英文名取前两个词首字母
  if (/[a-zA-Z]/.test(teamName)) {
    const parts = teamName.split(' ');
    if (parts.length >= 2) {
      return (parts[0][0] + parts[1][0]).toUpperCase();
    }
    return teamName.substring(0, 2).toUpperCase();
  }
  // 中文名取前两个字
  return teamName.substring(0, 2);
}

// 动态哈希计算颜色值
function getTeamColor(teamName) {
  let hash = 0;
  for (let i = 0; i < teamName.length; i++) {
    hash = teamName.charCodeAt(i) + ((hash << 5) - hash);
  }
  const c = (hash & 0x00FFFFFF).toString(16).toUpperCase();
  return '#' + '00000'.substring(0, 6 - c.length) + c;
}

// 模版动态解析：为真实比赛生成深度预测说明
function generateExplanation(home, away, marketType, tipCode, lang) {
  const templates = {
    '1X2': {
      zh: [
        `${home}近期战意饱满，坐拥主场之利能更好地发挥其高位压迫战术。结合赔率和主力阵容整齐度，预测其本次胜算极大。`,
        `${away}客场打法相对保守，但近期防守反击效率回升。两队球风相克，主队很难轻松攻破客队防线，倾向不败或平局结局。`
      ],
      en: [
        `${home} enters this match with strong motivation. Their high-press tactical approach is usually highly effective at home. We predict a home victory.`,
        `${away} adopts a conservative counter-attacking style away. Their defensive discipline makes them tough to break down. We lean towards an undefeated outcome or a draw.`
      ]
    },
    'GOALS': {
      zh: [
        `交战双方前场均拥有极具爆发力的边锋，防守端并非牢不可破，本场极有可能演变成进球大战。`,
        `两队近来防线极为稳固，打法倾向于中场拦截与肉搏战，产生大比分的几率偏低。`
      ],
      en: [
        `Both teams feature explosive wingers on offense and minor gaps in defense. We expect an open game with multiple goals.`,
        `Both sides have been highly structured defensively of late. Tactics will likely center on midfield battles, keeping the scoreline low.`
      ]
    },
    'GG_NG': {
      zh: [
        `历史交锋表明两队遭遇时互攻倾向明显，两队前锋近期脚风颇顺，双方破门概率极高。`,
        `主队擅长控球消耗对手，客队进攻端火力略显单薄，本场预计至少有一方将交出白卷。`
      ],
      en: [
        `Historical head-to-head records suggest a strong tendency for open play. Both frontlines are in great form, making GG highly likely.`,
        `The home side excels at controlling tempo, while the visitors lack attacking depth. We anticipate at least one side failing to score.`
      ]
    }
  };

  const pool = templates[marketType]?.[lang] || ['Analysis generated by AI model.', '分析数据同步中。'];
  // 确定性随机：根据主客队名字哈希锁定同一个文案，避免每次抓取文字都在变
  const hash = home.length + away.length + (tipCode.charCodeAt(0) || 0);
  return pool[hash % pool.length];
}

// 模拟生成积分榜大表
function generateMockStandings(homeId, awayId, allTeams) {
  // 简易积分表
  return allTeams.slice(0, 8).map((team, idx) => {
    const wins = 24 - idx * 2;
    const draws = 6;
    const losses = 38 - wins - draws;
    return {
      position: idx + 1,
      teamId: team.id,
      played: 38,
      wins,
      draws,
      losses,
      goalsFor: 78 - idx * 4,
      goalsAgainst: 28 + idx * 3,
      points: wins * 3 + draws
    };
  });
}

// 核心同步逻辑
async function sync() {
  console.log('🔄 开始从懂球帝公开接口获取真实赛事...');

  const datesToFetch = [
    getDateStringOffset(-1), // 昨天
    getDateStringOffset(0),  // 今天
    getDateStringOffset(1),  // 明天
    getDateStringOffset(2)   // 后天
  ];

  const allMatches = [];
  const processedTeams = new Map(); // 缓存生成的 Team
  const processedLeagues = new Map();
  const processedCountries = new Map();

  for (const dateStr of datesToFetch) {
    console.log(`📅 正在抓取日期: ${dateStr}`);
    const url = `https://sport-data.dongqiudi.com/sportdata/v1/game/list/football?date=${dateStr}`;
    
    try {
      const response = await httpGet(url);
      if (!response.data || !Array.isArray(response.data)) {
        console.log(`⚠️ 日期 ${dateStr} 未返回有效赛事数据。`);
        continue;
      }

      // 懂球帝返回的数据中，赛事可能直接平铺，也可能按时间排序。
      // 我们筛选出主要的比赛进行展示，避免垃圾小联赛过多。一般我们可以筛选出含有主流中超、五大联赛、欧冠等字眼的赛事。
      // 如果没有筛选，就截取前 15 场作为今日精选。
      const rawMatches = response.data;
      
      const filteredRaw = rawMatches.filter(item => {
        const cName = item.competition_name || '';
        return (
          cName.includes('英超') || 
          cName.includes('西甲') || 
          cName.includes('德甲') || 
          cName.includes('意甲') || 
          cName.includes('法甲') || 
          cName.includes('欧冠') || 
          cName.includes('欧联') || 
          cName.includes('中超') || 
          cName.includes('美职联') || 
          cName.includes('日职') || 
          cName.includes('韩职') ||
          cName.includes('Premier League') ||
          cName.includes('La Liga') ||
          cName.includes('Serie A') ||
          cName.includes('Bundesliga')
        );
      }).slice(0, 20); // 每天最多保留 20 场精选比赛

      // 如果过滤出来的赛事太少，就拿全部比赛的前 15 场补足
      const finalRawList = filteredRaw.length >= 5 ? filteredRaw : rawMatches.slice(0, 15);

      for (let i = 0; i < finalRawList.length; i++) {
        const item = finalRawList[i];
        
        // 提取并注册球队
        const hName = item.home_team_name || 'Home';
        const aName = item.away_team_name || 'Away';
        const hId = `team_h_${hName.replace(/\s+/g, '_')}`;
        const aId = `team_a_${aName.replace(/\s+/g, '_')}`;

        if (!processedTeams.has(hId)) {
          processedTeams.set(hId, {
            id: hId,
            name: { zh: hName, en: item.home_team_english_name || hName },
            shortName: { zh: hName.substring(0, 5), en: (item.home_team_english_name || hName).substring(0, 8) },
            logo: getTeamLogoAbbr(hName),
            value: `${Math.floor(80 + Math.random() * 800)}M €`,
            color: getTeamColor(hName)
          });
        }
        if (!processedTeams.has(aId)) {
          processedTeams.set(aId, {
            id: aId,
            name: { zh: aName, en: item.away_team_english_name || aName },
            shortName: { zh: aName.substring(0, 5), en: (item.away_team_english_name || aName).substring(0, 8) },
            logo: getTeamLogoAbbr(aName),
            value: `${Math.floor(80 + Math.random() * 800)}M €`,
            color: getTeamColor(aName)
          });
        }

        // 提取并注册联赛
        const compName = item.competition_name || '其他赛事';
        const compId = `league_${compName.replace(/\s+/g, '_')}`;
        if (!processedLeagues.has(compId)) {
          processedLeagues.set(compId, {
            id: compId,
            name: { zh: compName, en: item.competition_english_name || compName },
            shortName: { zh: compName, en: (item.competition_english_name || compName).substring(0, 6) },
            countryId: 'global',
            isImportant: true
          });
        }

        // 开赛时间
        const kickoffTime = item.start_time || new Date().toISOString();

        // 比赛状态匹配：懂球帝 status 可能为 "Fixture"、"Played" 或数字比分/进行中分钟
        let status = 'SCHEDULED';
        if (item.status === 'Played' || item.status === '结束' || item.status === 'FT') {
          status = 'FINISHED';
        } else if (item.status === 'LIVE' || (item.status && item.status.includes('半场')) || /\d+/.test(item.status)) {
          status = 'LIVE';
        }

        // 比赛比分
        const scoreHome = item.home_score !== undefined ? parseInt(item.home_score) : undefined;
        const scoreAway = item.away_score !== undefined ? parseInt(item.away_score) : undefined;

        // 确定性随机生成本场初始赔率 (基底赔率根据主客队实力随机)
        const randSeed = hName.length + aName.length;
        const odds1 = parseFloat((1.4 + (randSeed % 10) * 0.15).toFixed(2));
        const oddsX = parseFloat((3.0 + (randSeed % 5) * 0.2).toFixed(2));
        const odds2 = parseFloat((1.8 + (randSeed % 7) * 0.3).toFixed(2));

        // 数学概率生成确定性预测 (确保每次运行，同一场比赛的预测在未结束时保持一致)
        const homeWinProb = Math.round((1 / odds1) * 100);
        const awayWinProb = Math.round((1 / odds2) * 100);
        const drawProb = 100 - homeWinProb - awayWinProb;
        
        let bestTipCode = '1';
        let bestTipTextZH = `主胜 (${hName})`;
        let bestTipTextEN = `Home Win (${item.home_team_english_name || hName})`;
        let bestOddsValue = odds1;
        let bestTrust = homeWinProb;

        if (awayWinProb > homeWinProb && awayWinProb > drawProb) {
          bestTipCode = '2';
          bestTipTextZH = `客胜 (${aName})`;
          bestTipTextEN = `Away Win (${item.away_team_english_name || aName})`;
          bestOddsValue = odds2;
          bestTrust = awayWinProb;
        } else if (drawProb > homeWinProb && drawProb > awayWinProb) {
          bestTipCode = 'X';
          bestTipTextZH = '平局 (Draw)';
          bestTipTextEN = 'Draw';
          bestOddsValue = oddsX;
          bestTrust = drawProb;
        }

        // 保证 Trust 在合理范围 [55, 95]
        bestTrust = Math.max(55, Math.min(95, bestTrust));

        // 构建预测池
        const predictions = [
          {
            marketType: '1X2',
            tipCode: bestTipCode,
            tipLabel: { zh: bestTipTextZH, en: bestTipTextEN },
            odds: bestOddsValue,
            trustScore: bestTrust,
            explanation: {
              zh: generateExplanation(hName, aName, '1X2', bestTipCode, 'zh'),
              en: generateExplanation(hName, aName, '1X2', bestTipCode, 'en')
            },
            visibilityStatus: 'FREE',
            resultStatus: status === 'FINISHED' 
              ? ((scoreHome > scoreAway && bestTipCode === '1') || (scoreHome === scoreAway && bestTipCode === 'X') || (scoreHome < scoreAway && bestTipCode === '2') ? 'WON' : 'LOST')
              : 'PENDING'
          },
          {
            marketType: 'GOALS',
            tipCode: (randSeed % 2 === 0) ? 'O2.5' : 'U2.5',
            tipLabel: (randSeed % 2 === 0) ? { zh: '大于 2.5 球', en: 'Over 2.5 Goals' } : { zh: '小于 2.5 球', en: 'Under 2.5 Goals' },
            odds: parseFloat((1.65 + (randSeed % 4) * 0.1).toFixed(2)),
            trustScore: Math.floor(58 + (randSeed % 35)),
            explanation: {
              zh: generateExplanation(hName, aName, 'GOALS', (randSeed % 2 === 0) ? 'O2.5' : 'U2.5', 'zh'),
              en: generateExplanation(hName, aName, 'GOALS', (randSeed % 2 === 0) ? 'O2.5' : 'U2.5', 'en')
            },
            visibilityStatus: 'PREMIUM',
            resultStatus: status === 'FINISHED'
              ? ((scoreHome + scoreAway > 2.5 && randSeed % 2 === 0) || (scoreHome + scoreAway < 2.5 && randSeed % 2 !== 0) ? 'WON' : 'LOST')
              : 'PENDING'
          },
          {
            marketType: 'GG_NG',
            tipCode: (randSeed % 3 !== 0) ? 'GG' : 'NG',
            tipLabel: (randSeed % 3 !== 0) ? { zh: '双方进球 (GG)', en: 'Both Teams to Score (GG)' } : { zh: '至少一方零封 (NG)', en: 'No Goal (NG)' },
            odds: parseFloat((1.70 + (randSeed % 3) * 0.08).toFixed(2)),
            trustScore: Math.floor(60 + (randSeed % 30)),
            explanation: {
              zh: generateExplanation(hName, aName, 'GG_NG', (randSeed % 3 !== 0) ? 'GG' : 'NG', 'zh'),
              en: generateExplanation(hName, aName, 'GG_NG', (randSeed % 3 !== 0) ? 'GG' : 'NG', 'en')
            },
            visibilityStatus: 'PREMIUM',
            resultStatus: status === 'FINISHED'
              ? ((scoreHome > 0 && scoreAway > 0 && randSeed % 3 !== 0) || ((scoreHome === 0 || scoreAway === 0) && randSeed % 3 === 0) ? 'WON' : 'LOST')
              : 'PENDING'
          }
        ];

        // 稳胆 Best Tip
        predictions.push({
          marketType: 'BEST',
          tipCode: bestTipCode,
          tipLabel: { zh: `稳胆: ${bestTipTextZH}`, en: `Best: ${bestTipTextEN}` },
          odds: bestOddsValue,
          trustScore: Math.min(99, bestTrust + 2),
          explanation: {
            zh: `【AI 精选稳胆】经过懂球帝实时赛事库分析，本场 ${hName} vs ${aName} 模型拟合极高。建议重点关注。`,
            en: `[AI Elite Tip] Analyzing real-time squad strength for ${hName} vs ${aName}. High probability profile.`
          },
          visibilityStatus: 'PREMIUM',
          resultStatus: predictions[0].resultStatus
        });

        // 比赛技术统计
        const xG_h = parseFloat((1.0 + (randSeed % 8) * 0.2).toFixed(2));
        const xG_a = parseFloat((0.8 + (randSeed % 5) * 0.2).toFixed(2));

        const matchObj = {
          id: `real_match_${item.id || randSeed + i}`,
          homeTeamId: hId,
          awayTeamId: aId,
          leagueId: compId,
          countryId: 'global',
          kickoffTime,
          status,
          scoreHome,
          scoreAway,
          odds: { odds1, oddsX, odds2 },
          predictions,
          stats: {
            xG: { home: xG_h, away: xG_a },
            possession: { home: 50 + (randSeed % 15), away: 50 - (randSeed % 15) },
            shots: { home: 10 + (randSeed % 8), away: 8 + (randSeed % 6) },
            shotsOnTarget: { home: 3 + (randSeed % 4), away: 2 + (randSeed % 3) },
            corners: { home: 4 + (randSeed % 5), away: 3 + (randSeed % 4) },
            fouls: { home: 9 + (randSeed % 6), away: 10 + (randSeed % 5) },
            offsides: { home: randSeed % 3, away: randSeed % 4 },
            yellowCards: { home: randSeed % 4, away: randSeed % 5 },
            redCards: { home: 0, away: 0 }
          },
          recentForm: {
            home: {
              recentMatches: [
                { opponentId: 'opp', opponentName: { zh: '历史对手A', en: 'Opponent A' }, isHome: true, ourScore: 2, oppScore: 1, date: '2026-05-15', competition: { zh: compName, en: compName } }
              ],
              statsLast10: { wins: 5, draws: 3, losses: 2, over1_5: 80, over2_5: 60, over3_5: 30, bothToScore: 50, upsetWins: 1, upsetLosses: 0 }
            },
            away: {
              recentMatches: [
                { opponentId: 'opp', opponentName: { zh: '历史对手B', en: 'Opponent B' }, isHome: false, ourScore: 1, oppScore: 1, date: '2026-05-14', competition: { zh: compName, en: compName } }
              ],
              statsLast10: { wins: 4, draws: 4, losses: 2, over1_5: 75, over2_5: 50, over3_5: 20, bothToScore: 60, upsetWins: 0, upsetLosses: 1 }
            }
          },
          h2h: [
            { date: '2025-10-10', homeScore: 2, awayScore: 0, homeTeamId: hId, awayTeamId: aId, competition: { zh: compName, en: compName } }
          ],
          standings: generateMockStandings(hId, aId, Array.from(processedTeams.values()))
        };

        allMatches.push(matchObj);
      }
    } catch (e) {
      console.log(`❌ 抓取日期 ${dateStr} 时出错: ${e.message}`);
    }
  }

  // 写入 JSON 文件到 public 文件夹（若不存在则创建 public 文件夹）
  const publicDir = path.join(__dirname, '..', 'public');
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  const outputPath = path.join(publicDir, 'matches.json');
  fs.writeFileSync(outputPath, JSON.stringify(allMatches, null, 2));

  console.log(`✅ 同步完毕！共处理了 ${allMatches.length} 场真实赛事，已成功写入至 ${outputPath}`);
}

sync();
