"use strict";
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const ts = require('typescript');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'combo-view-'));
const source = fs.readFileSync(path.join(__dirname, '../src/services/dailyComboView.ts'), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS } });
const file = path.join(temporary, 'view.cjs'); fs.writeFileSync(file, compiled.outputText);
const { visibleCombo, parseComboLedger } = require(file);
after(() => fs.rmSync(temporary, { recursive: true, force: true }));
const now = Date.parse('2026-09-16T10:00:00Z');
const row = (size) => ({ size, totalOdds: 6, legs: Array.from({ length: size }, (_, i) => ({ matchId: String(i), sourceMatchId: String(i), tipCode: '1', market: 'HAD', odds: 2, kickoffTime: '2026-09-16T15:00:00Z', cutoffTime: '2026-09-16T14:00:00Z' })) });
const base = () => ({ businessDate: '2026-09-16', updatedAt: new Date(now).toISOString(), publishable: true, today: [], previews: [row(2), row(3)], modelRiskStable: false, formalCount: 0 });
test('zero formal single picks cannot hide independent previews', () => { const x = base(); assert.ok(visibleCombo(x, 2, now)); assert.ok(visibleCombo(x, 3, now)); });
test('one frozen size cannot hide the other preview', () => { const x = base(); x.today = [{ ...row(2), businessDate: x.businessDate, frozenAt: '2026-09-16T09:00:00Z' }]; assert.ok(visibleCombo(x, 2, now).frozenAt); assert.equal(visibleCombo(x, 3, now).size, 3); });
test('stale previews are not presented as current', () => assert.equal(visibleCombo({ ...base(), updatedAt: '2026-09-16T08:00:00Z' }, 2, now), null));
test('started previews expire but frozen records remain', () => { const x = base(); x.previews[0].legs[0].kickoffTime = new Date(now).toISOString(); assert.equal(visibleCombo(x, 2, now), null); x.today = [{ ...row(2), businessDate: x.businessDate, frozenAt: '2026-09-16T09:00:00Z' }]; assert.ok(visibleCombo(x, 2, now + 4 * 3600000, true)); });
test('wrong business day is not shown as today', () => assert.equal(visibleCombo({ ...base(), businessDate: '2026-09-15' }, 2, now), null));
test('read errors remain distinct from empty pools', () => { assert.throws(() => parseComboLedger({ previews: 'oops', today: [] })); assert.equal(visibleCombo(base(), 2, now, true), null); });
