import type { Decision, PublishedScores, SelectionQuality, SupplementaryResearch, SingleRow } from '../../services/recommendationCenterView';
import { publishedDetailPresentation } from '../../services/publishedDetailPresentation';

import { selectionPriceStatus, selectionReferenceLabel } from '../../services/publishedRecommendationStatus.cjs';
export { selectionPriceStatus, selectionReferenceLabel };
export function SupplementaryResearchNote({research,decision,scoreDistribution,settlement,language,compact=false}:{research?:SupplementaryResearch|null;decision?:Decision;scoreDistribution?:PublishedScores|null;settlement?:SingleRow['supplementarySettlement'];language:'zh'|'en';compact?:boolean}){
 const coherent=decision?.primaryPickPolicyVersion==='coherent-market-primary-v1';
 if(!research&&!coherent)return null;
 const zh=language==='zh';
 const aligned=coherent?publishedDetailPresentation(decision!,[],scoreDistribution??null)?.primaryScore:null;
 const state=(key:'exactScore'|'totalGoals')=>({PENDING:zh?'待赛果':'Pending',WON:zh?'命中':'Hit',LOST:zh?'未命中':'Miss',VOID:zh?'无效':'Void',DISPUTED:zh?'赛果待核':'Disputed'}[settlement?.[key].state??'PENDING']);
 const frozenResearch=research&&<><p data-score-reference="frozen-research">{research.version==='supplementary-research-v2'?(zh?'全局比分分布参考':'Global score distribution reference'):(zh?'旧版同向比分研究':'Legacy aligned score research')} {research.exactScore.label} · {zh?'无条件概率':'Unconditional probability'} {(research.exactScore.probability*100).toFixed(1)}% · {state('exactScore')}</p>
  <p>{zh?'总进球分布最高项':'Total-goals distribution mode'} {research.totalGoals.label} · {zh?'无条件概率':'Unconditional probability'} {(research.totalGoals.probability*100).toFixed(1)}% · {state('totalGoals')}</p></>;
 return <div className="supplementary-research-note" data-supplementary-version={research?.version}>
  <strong>{zh?'比分与进球数 · 低置信参考':'Score & goals · low-confidence reference'}</strong>
  {coherent&&<p data-score-reference="aligned">{zh?'同向比分参考':'Aligned score reference'} {aligned?`${aligned.label} · ${zh?'无条件概率':'unconditional probability'} ${aligned.probability.toFixed(1)}%`:(zh?'暂不可用，同源冻结比分尚未取得':'unavailable; bound frozen scores are missing')}</p>}
  {compact&&frozenResearch?<details><summary>{zh?'查看分布参考':'View distribution references'}</summary>{frozenResearch}<small>{zh?'全局比分及总球沿用原冻结研究结算；未绑定官方 SP。':'Global scores and totals retain their frozen research settlement; no official SP bound.'}</small></details>:frozenResearch}
  <small>{compact?(zh?'低置信参考；同向比分不另计命中率。':'Low-confidence reference; aligned scores have no separate hit-rate claim.'):coherent?(zh?'同向比分不另计命中率；全局比分及总球沿用原冻结研究结算。未绑定官方 SP，模型尚未验证。':'Aligned scores have no separate hit-rate claim. Global scores and totals retain their frozen research settlement. No official SP bound; model unvalidated.'):(zh?'未绑定官方 SP；研究命中统计独立记录，模型尚未验证。':'No official SP bound; research hits tracked separately, model unvalidated.')}</small>
 </div>;
}

export function SelectionQualityNote({quality,language}:{quality?:SelectionQuality|null;language:'zh'|'en'}){
 if(!quality)return null;
 const zh=language==='zh';
 const labels:Record<string,string>=zh?{'anchor-market-unavailable':'冻结主方向缺少可用玩法或报价','quote-stale':'主方向报价已过期，等待真实新报价','input-evidence-unavailable':'本次模型输入依据尚未完整存档','input-arithmetic-unverified':'本次模型输入计算尚未核验','team-samples-insufficient':'实际参与模型的球队样本不足','model-lead-too-thin':'模型首位与第二方向差距较小，保留唯一首选并降低置信度','material-model-market-disagreement':'模型概率与同期官方 SP 去水概率明显冲突，暂不纳入串关','cross-track-direction-conflict':quality.assessedMarket==='HHAD'?'胜平负伴随方向与赛前参考方向不一致，保留观望限制':'同场赛前参考与发布方向相反，当前观望'}:{'anchor-market-unavailable':'Frozen primary market or price unavailable','quote-stale':'Primary quote expired; awaiting a fresh quote','input-evidence-unavailable':'Current model inputs are not fully archived','input-arithmetic-unverified':'Current input arithmetic is unverified','team-samples-insufficient':'Too few team samples in the active model','model-lead-too-thin':'Model lead is narrow; retain the single primary at low confidence','material-model-market-disagreement':'Model probability materially disagrees with the same-time official market; excluded from combos','cross-track-direction-conflict':quality.assessedMarket==='HHAD'?'The 1X2 companion conflicts with the pre-match reference; the watch restriction remains':'The pre-match reference conflicts with this published direction; watch only'};
 const pct=(n:number|null)=>n==null?'—':`${(n*100).toFixed(1)}%`;
 const priceStatus=selectionPriceStatus(quality);
 return <div className="selection-quality-note" data-selection-status={quality.status} data-price-status={priceStatus} style={{padding:'12px 14px',margin:'12px 0',border:'1px solid var(--border-color, #d8e2ea)',borderRadius:12,background:'var(--bg-secondary, #f4f7fa)'}}>
  <strong>{selectionReferenceLabel(quality,language)}{quality.assessmentBasis==='coherent-primary-anchor-v1'?` · ${zh?'主方向筛选':'Primary assessment'}（${quality.assessedMarket==='HHAD'?(zh?'让球':'HHAD'):(zh?'胜平负':'1X2')}）`:''}</strong>
  <p style={{margin:'6px 0',fontSize:13}}>{quality.qualified?(quality.version==='recommendation-selection-quality-v2'?(zh?'球队样本、模型领先幅度和同期 SP 分歧通过参考筛选；这不是校准、收益或命中率验证。模型概率最高只确定方向，不等于值得投注。':'Samples, model lead, and same-time SP disagreement pass the reference screen. This does not validate calibration, return, or accuracy. The top model probability only sets a direction, not a betting edge.'):(zh?'旧版仅核验球队样本与输入计算；不表示价格或命中率已验证。模型概率最高只确定方向，不等于值得投注。':'The legacy policy checks samples and input arithmetic only; price and accuracy remain unvalidated. The top model probability only sets a direction, not a betting edge.')):quality.reasons.map(r=>labels[r]||r).join('；')+(zh?'，暂不进入新串关。':' — excluded from new combos.')}</p>
  {quality.crossTrack&&<p role="note" data-cross-track-conflict="true" style={{margin:'6px 0',fontSize:12}}>{quality.assessedMarket==='HHAD'&&<strong>{zh?'胜平负伴随方向与参考方向不一致。':'The 1X2 companion differs from the reference. '}</strong>}{zh?`同场已核验赛前参考在 ${new Date(quality.crossTrack.referenceRecordedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})} 记录了${({'1':'主胜',X:'平局','2':'客胜'} as const)[quality.crossTrack.referenceTipCode]}；${quality.crossTrack.knownAtPublication?'发布时已有分歧':'该分歧在本条发布后才记录'}。两条冻结方向保留供复盘，不把任一方向包装成当前确定推荐。`:`An attested pre-match reference recorded ${quality.crossTrack.referenceTipCode} at ${quality.crossTrack.referenceRecordedAt}; ${quality.crossTrack.knownAtPublication?'the disagreement was known at publication':'it arrived after this decision'}. Both frozen directions remain available for review.`}</p>}
  <small>{zh?'与第二方向差距':'Lead over second'} {pct(quality.probabilityLead)} · {zh?'市场概率':'Market probability'} {pct(quality.marketProbability)} · {zh?'模型与市场差值':'Model minus market'} {pct(quality.modelMarketGap)}</small>
  <p style={{margin:'6px 0 0',fontSize:12}}>{zh?'冻结发布模型期望值':'Frozen published model expected value'} {pct(quality.expectedValue)} · {quality.marketProbability==null?(zh?'市场热门不可判定':'Market favorite unavailable'):quality.marketFavorite?(zh?'方向与市场热门一致':'Matches market favorite'):(zh?'方向与市场热门不同':'Differs from market favorite')}</p>
  {priceStatus==='unsupported'&&<p className="selection-quality-note__negative" role="note" data-model-ev="negative" style={{margin:'9px 0 0',padding:'8px 10px',borderLeft:'3px solid #b65a25',borderRadius:6,background:'#fff2e7',color:'#793d1c',fontSize:12,lineHeight:1.5}}>{zh?'按冻结模型概率 × 冻结 SP 计算，期望值为负；不能仅因 SP 低或模型概率最高就视为值得投注。':'Frozen model probability × frozen SP implies negative expected value; neither low SP nor the highest model probability establishes a bet.'}</p>}
 </div>;
}
